// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/abusereport"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// AbuseReportCreate is the builder for creating a AbuseReport entity.
type AbuseReportCreate struct {
	config
	mutation *AbuseReportMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (arc *AbuseReportCreate) SetCreatedAt(t time.Time) *AbuseReportCreate {
	arc.mutation.SetCreatedAt(t)
	return arc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableCreatedAt(t *time.Time) *AbuseReportCreate {
	if t != nil {
		arc.SetCreatedAt(*t)
	}
	return arc
}

// SetUpdatedAt sets the "updated_at" field.
func (arc *AbuseReportCreate) SetUpdatedAt(t time.Time) *AbuseReportCreate {
	arc.mutation.SetUpdatedAt(t)
	return arc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableUpdatedAt(t *time.Time) *AbuseReportCreate {
	if t != nil {
		arc.SetUpdatedAt(*t)
	}
	return arc
}

// SetDeletedAt sets the "deleted_at" field.
func (arc *AbuseReportCreate) SetDeletedAt(t time.Time) *AbuseReportCreate {
	arc.mutation.SetDeletedAt(t)
	return arc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableDeletedAt(t *time.Time) *AbuseReportCreate {
	if t != nil {
		arc.SetDeletedAt(*t)
	}
	return arc
}

// SetFolderPath sets the "folder_path" field.
func (arc *AbuseReportCreate) SetFolderPath(s string) *AbuseReportCreate {
	arc.mutation.SetFolderPath(s)
	return arc
}

// SetNillableFolderPath sets the "folder_path" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableFolderPath(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetFolderPath(*s)
	}
	return arc
}

// SetReason sets the "reason" field.
func (arc *AbuseReportCreate) SetReason(s string) *AbuseReportCreate {
	arc.mutation.SetReason(s)
	return arc
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableReason(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetReason(*s)
	}
	return arc
}

// SetDescription sets the "description" field.
func (arc *AbuseReportCreate) SetDescription(s string) *AbuseReportCreate {
	arc.mutation.SetDescription(s)
	return arc
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableDescription(s *string) *AbuseReportCreate {
	if s != nil {
		arc.SetDescription(*s)
	}
	return arc
}

// SetStatus sets the "status" field.
func (arc *AbuseReportCreate) SetStatus(a abusereport.Status) *AbuseReportCreate {
	arc.mutation.SetStatus(a)
	return arc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableStatus(a *abusereport.Status) *AbuseReportCreate {
	if a != nil {
		arc.SetStatus(*a)
	}
	return arc
}

// SetRawContent sets the "raw_content" field.
func (arc *AbuseReportCreate) SetRawContent(tc *types.AuditContent) *AbuseReportCreate {
	arc.mutation.SetRawContent(tc)
	return arc
}

// SetReporterUser sets the "reporter_user" field.
func (arc *AbuseReportCreate) SetReporterUser(i int) *AbuseReportCreate {
	arc.mutation.SetReporterUser(i)
	return arc
}

// SetNillableReporterUser sets the "reporter_user" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableReporterUser(i *int) *AbuseReportCreate {
	if i != nil {
		arc.SetReporterUser(*i)
	}
	return arc
}

// SetReportedUser sets the "reported_user" field.
func (arc *AbuseReportCreate) SetReportedUser(i int) *AbuseReportCreate {
	arc.mutation.SetReportedUser(i)
	return arc
}

// SetNillableReportedUser sets the "reported_user" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableReportedUser(i *int) *AbuseReportCreate {
	if i != nil {
		arc.SetReportedUser(*i)
	}
	return arc
}

// SetShareReports sets the "share_reports" field.
func (arc *AbuseReportCreate) SetShareReports(i int) *AbuseReportCreate {
	arc.mutation.SetShareReports(i)
	return arc
}

// SetNillableShareReports sets the "share_reports" field if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableShareReports(i *int) *AbuseReportCreate {
	if i != nil {
		arc.SetShareReports(*i)
	}
	return arc
}

// SetReporterID sets the "reporter" edge to the User entity by ID.
func (arc *AbuseReportCreate) SetReporterID(id int) *AbuseReportCreate {
	arc.mutation.SetReporterID(id)
	return arc
}

// SetNillableReporterID sets the "reporter" edge to the User entity by ID if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableReporterID(id *int) *AbuseReportCreate {
	if id != nil {
		arc = arc.SetReporterID(*id)
	}
	return arc
}

// SetReporter sets the "reporter" edge to the User entity.
func (arc *AbuseReportCreate) SetReporter(u *User) *AbuseReportCreate {
	return arc.SetReporterID(u.ID)
}

// SetReportedID sets the "reported" edge to the User entity by ID.
func (arc *AbuseReportCreate) SetReportedID(id int) *AbuseReportCreate {
	arc.mutation.SetReportedID(id)
	return arc
}

// SetNillableReportedID sets the "reported" edge to the User entity by ID if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableReportedID(id *int) *AbuseReportCreate {
	if id != nil {
		arc = arc.SetReportedID(*id)
	}
	return arc
}

// SetReported sets the "reported" edge to the User entity.
func (arc *AbuseReportCreate) SetReported(u *User) *AbuseReportCreate {
	return arc.SetReportedID(u.ID)
}

// SetShareID sets the "share" edge to the Share entity by ID.
func (arc *AbuseReportCreate) SetShareID(id int) *AbuseReportCreate {
	arc.mutation.SetShareID(id)
	return arc
}

// SetNillableShareID sets the "share" edge to the Share entity by ID if the given value is not nil.
func (arc *AbuseReportCreate) SetNillableShareID(id *int) *AbuseReportCreate {
	if id != nil {
		arc = arc.SetShareID(*id)
	}
	return arc
}

// SetShare sets the "share" edge to the Share entity.
func (arc *AbuseReportCreate) SetShare(s *Share) *AbuseReportCreate {
	return arc.SetShareID(s.ID)
}

// Mutation returns the AbuseReportMutation object of the builder.
func (arc *AbuseReportCreate) Mutation() *AbuseReportMutation {
	return arc.mutation
}

// Save creates the AbuseReport in the database.
func (arc *AbuseReportCreate) Save(ctx context.Context) (*AbuseReport, error) {
	if err := arc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, arc.sqlSave, arc.mutation, arc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (arc *AbuseReportCreate) SaveX(ctx context.Context) *AbuseReport {
	v, err := arc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arc *AbuseReportCreate) Exec(ctx context.Context) error {
	_, err := arc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arc *AbuseReportCreate) ExecX(ctx context.Context) {
	if err := arc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (arc *AbuseReportCreate) defaults() error {
	if _, ok := arc.mutation.CreatedAt(); !ok {
		if abusereport.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized abusereport.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := abusereport.DefaultCreatedAt()
		arc.mutation.SetCreatedAt(v)
	}
	if _, ok := arc.mutation.UpdatedAt(); !ok {
		if abusereport.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized abusereport.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := abusereport.DefaultUpdatedAt()
		arc.mutation.SetUpdatedAt(v)
	}
	if _, ok := arc.mutation.Status(); !ok {
		v := abusereport.DefaultStatus
		arc.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (arc *AbuseReportCreate) check() error {
	if _, ok := arc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AbuseReport.created_at"`)}
	}
	if _, ok := arc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AbuseReport.updated_at"`)}
	}
	if _, ok := arc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "AbuseReport.status"`)}
	}
	if v, ok := arc.mutation.Status(); ok {
		if err := abusereport.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AbuseReport.status": %w`, err)}
		}
	}
	return nil
}

func (arc *AbuseReportCreate) sqlSave(ctx context.Context) (*AbuseReport, error) {
	if err := arc.check(); err != nil {
		return nil, err
	}
	_node, _spec := arc.createSpec()
	if err := sqlgraph.CreateNode(ctx, arc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	arc.mutation.id = &_node.ID
	arc.mutation.done = true
	return _node, nil
}

func (arc *AbuseReportCreate) createSpec() (*AbuseReport, *sqlgraph.CreateSpec) {
	var (
		_node = &AbuseReport{config: arc.config}
		_spec = sqlgraph.NewCreateSpec(abusereport.Table, sqlgraph.NewFieldSpec(abusereport.FieldID, field.TypeInt))
	)

	if id, ok := arc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = arc.conflict
	if value, ok := arc.mutation.CreatedAt(); ok {
		_spec.SetField(abusereport.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := arc.mutation.UpdatedAt(); ok {
		_spec.SetField(abusereport.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := arc.mutation.DeletedAt(); ok {
		_spec.SetField(abusereport.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := arc.mutation.FolderPath(); ok {
		_spec.SetField(abusereport.FieldFolderPath, field.TypeString, value)
		_node.FolderPath = value
	}
	if value, ok := arc.mutation.Reason(); ok {
		_spec.SetField(abusereport.FieldReason, field.TypeString, value)
		_node.Reason = value
	}
	if value, ok := arc.mutation.Description(); ok {
		_spec.SetField(abusereport.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := arc.mutation.Status(); ok {
		_spec.SetField(abusereport.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := arc.mutation.RawContent(); ok {
		_spec.SetField(abusereport.FieldRawContent, field.TypeJSON, value)
		_node.RawContent = value
	}
	if nodes := arc.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   abusereport.ReporterTable,
			Columns: []string{abusereport.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReporterUser = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := arc.mutation.ReportedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   abusereport.ReportedTable,
			Columns: []string{abusereport.ReportedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReportedUser = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := arc.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   abusereport.ShareTable,
			Columns: []string{abusereport.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShareReports = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AbuseReport.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AbuseReportUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (arc *AbuseReportCreate) OnConflict(opts ...sql.ConflictOption) *AbuseReportUpsertOne {
	arc.conflict = opts
	return &AbuseReportUpsertOne{
		create: arc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (arc *AbuseReportCreate) OnConflictColumns(columns ...string) *AbuseReportUpsertOne {
	arc.conflict = append(arc.conflict, sql.ConflictColumns(columns...))
	return &AbuseReportUpsertOne{
		create: arc,
	}
}

type (
	// AbuseReportUpsertOne is the builder for "upsert"-ing
	//  one AbuseReport node.
	AbuseReportUpsertOne struct {
		create *AbuseReportCreate
	}

	// AbuseReportUpsert is the "OnConflict" setter.
	AbuseReportUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *AbuseReportUpsert) SetUpdatedAt(v time.Time) *AbuseReportUpsert {
	u.Set(abusereport.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateUpdatedAt() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AbuseReportUpsert) SetDeletedAt(v time.Time) *AbuseReportUpsert {
	u.Set(abusereport.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateDeletedAt() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AbuseReportUpsert) ClearDeletedAt() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldDeletedAt)
	return u
}

// SetFolderPath sets the "folder_path" field.
func (u *AbuseReportUpsert) SetFolderPath(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldFolderPath, v)
	return u
}

// UpdateFolderPath sets the "folder_path" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateFolderPath() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldFolderPath)
	return u
}

// ClearFolderPath clears the value of the "folder_path" field.
func (u *AbuseReportUpsert) ClearFolderPath() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldFolderPath)
	return u
}

// SetReason sets the "reason" field.
func (u *AbuseReportUpsert) SetReason(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldReason, v)
	return u
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateReason() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldReason)
	return u
}

// ClearReason clears the value of the "reason" field.
func (u *AbuseReportUpsert) ClearReason() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldReason)
	return u
}

// SetDescription sets the "description" field.
func (u *AbuseReportUpsert) SetDescription(v string) *AbuseReportUpsert {
	u.Set(abusereport.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateDescription() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *AbuseReportUpsert) ClearDescription() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldDescription)
	return u
}

// SetStatus sets the "status" field.
func (u *AbuseReportUpsert) SetStatus(v abusereport.Status) *AbuseReportUpsert {
	u.Set(abusereport.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateStatus() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldStatus)
	return u
}

// SetRawContent sets the "raw_content" field.
func (u *AbuseReportUpsert) SetRawContent(v *types.AuditContent) *AbuseReportUpsert {
	u.Set(abusereport.FieldRawContent, v)
	return u
}

// UpdateRawContent sets the "raw_content" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateRawContent() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldRawContent)
	return u
}

// ClearRawContent clears the value of the "raw_content" field.
func (u *AbuseReportUpsert) ClearRawContent() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldRawContent)
	return u
}

// SetReporterUser sets the "reporter_user" field.
func (u *AbuseReportUpsert) SetReporterUser(v int) *AbuseReportUpsert {
	u.Set(abusereport.FieldReporterUser, v)
	return u
}

// UpdateReporterUser sets the "reporter_user" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateReporterUser() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldReporterUser)
	return u
}

// ClearReporterUser clears the value of the "reporter_user" field.
func (u *AbuseReportUpsert) ClearReporterUser() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldReporterUser)
	return u
}

// SetReportedUser sets the "reported_user" field.
func (u *AbuseReportUpsert) SetReportedUser(v int) *AbuseReportUpsert {
	u.Set(abusereport.FieldReportedUser, v)
	return u
}

// UpdateReportedUser sets the "reported_user" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateReportedUser() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldReportedUser)
	return u
}

// ClearReportedUser clears the value of the "reported_user" field.
func (u *AbuseReportUpsert) ClearReportedUser() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldReportedUser)
	return u
}

// SetShareReports sets the "share_reports" field.
func (u *AbuseReportUpsert) SetShareReports(v int) *AbuseReportUpsert {
	u.Set(abusereport.FieldShareReports, v)
	return u
}

// UpdateShareReports sets the "share_reports" field to the value that was provided on create.
func (u *AbuseReportUpsert) UpdateShareReports() *AbuseReportUpsert {
	u.SetExcluded(abusereport.FieldShareReports)
	return u
}

// ClearShareReports clears the value of the "share_reports" field.
func (u *AbuseReportUpsert) ClearShareReports() *AbuseReportUpsert {
	u.SetNull(abusereport.FieldShareReports)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AbuseReportUpsertOne) UpdateNewValues() *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(abusereport.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *AbuseReportUpsertOne) Ignore() *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AbuseReportUpsertOne) DoNothing() *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AbuseReportCreate.OnConflict
// documentation for more info.
func (u *AbuseReportUpsertOne) Update(set func(*AbuseReportUpsert)) *AbuseReportUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AbuseReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AbuseReportUpsertOne) SetUpdatedAt(v time.Time) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateUpdatedAt() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AbuseReportUpsertOne) SetDeletedAt(v time.Time) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateDeletedAt() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AbuseReportUpsertOne) ClearDeletedAt() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearDeletedAt()
	})
}

// SetFolderPath sets the "folder_path" field.
func (u *AbuseReportUpsertOne) SetFolderPath(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetFolderPath(v)
	})
}

// UpdateFolderPath sets the "folder_path" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateFolderPath() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateFolderPath()
	})
}

// ClearFolderPath clears the value of the "folder_path" field.
func (u *AbuseReportUpsertOne) ClearFolderPath() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearFolderPath()
	})
}

// SetReason sets the "reason" field.
func (u *AbuseReportUpsertOne) SetReason(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateReason() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *AbuseReportUpsertOne) ClearReason() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReason()
	})
}

// SetDescription sets the "description" field.
func (u *AbuseReportUpsertOne) SetDescription(v string) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateDescription() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AbuseReportUpsertOne) ClearDescription() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *AbuseReportUpsertOne) SetStatus(v abusereport.Status) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateStatus() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateStatus()
	})
}

// SetRawContent sets the "raw_content" field.
func (u *AbuseReportUpsertOne) SetRawContent(v *types.AuditContent) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetRawContent(v)
	})
}

// UpdateRawContent sets the "raw_content" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateRawContent() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateRawContent()
	})
}

// ClearRawContent clears the value of the "raw_content" field.
func (u *AbuseReportUpsertOne) ClearRawContent() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearRawContent()
	})
}

// SetReporterUser sets the "reporter_user" field.
func (u *AbuseReportUpsertOne) SetReporterUser(v int) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReporterUser(v)
	})
}

// UpdateReporterUser sets the "reporter_user" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateReporterUser() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReporterUser()
	})
}

// ClearReporterUser clears the value of the "reporter_user" field.
func (u *AbuseReportUpsertOne) ClearReporterUser() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReporterUser()
	})
}

// SetReportedUser sets the "reported_user" field.
func (u *AbuseReportUpsertOne) SetReportedUser(v int) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReportedUser(v)
	})
}

// UpdateReportedUser sets the "reported_user" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateReportedUser() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReportedUser()
	})
}

// ClearReportedUser clears the value of the "reported_user" field.
func (u *AbuseReportUpsertOne) ClearReportedUser() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReportedUser()
	})
}

// SetShareReports sets the "share_reports" field.
func (u *AbuseReportUpsertOne) SetShareReports(v int) *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetShareReports(v)
	})
}

// UpdateShareReports sets the "share_reports" field to the value that was provided on create.
func (u *AbuseReportUpsertOne) UpdateShareReports() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateShareReports()
	})
}

// ClearShareReports clears the value of the "share_reports" field.
func (u *AbuseReportUpsertOne) ClearShareReports() *AbuseReportUpsertOne {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearShareReports()
	})
}

// Exec executes the query.
func (u *AbuseReportUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AbuseReportCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AbuseReportUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *AbuseReportUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *AbuseReportUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *AbuseReportCreate) SetRawID(t int) *AbuseReportCreate {
	m.mutation.SetRawID(t)
	return m
}

// AbuseReportCreateBulk is the builder for creating many AbuseReport entities in bulk.
type AbuseReportCreateBulk struct {
	config
	err      error
	builders []*AbuseReportCreate
	conflict []sql.ConflictOption
}

// Save creates the AbuseReport entities in the database.
func (arcb *AbuseReportCreateBulk) Save(ctx context.Context) ([]*AbuseReport, error) {
	if arcb.err != nil {
		return nil, arcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(arcb.builders))
	nodes := make([]*AbuseReport, len(arcb.builders))
	mutators := make([]Mutator, len(arcb.builders))
	for i := range arcb.builders {
		func(i int, root context.Context) {
			builder := arcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AbuseReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, arcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = arcb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, arcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, arcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (arcb *AbuseReportCreateBulk) SaveX(ctx context.Context) []*AbuseReport {
	v, err := arcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (arcb *AbuseReportCreateBulk) Exec(ctx context.Context) error {
	_, err := arcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (arcb *AbuseReportCreateBulk) ExecX(ctx context.Context) {
	if err := arcb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.AbuseReport.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.AbuseReportUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (arcb *AbuseReportCreateBulk) OnConflict(opts ...sql.ConflictOption) *AbuseReportUpsertBulk {
	arcb.conflict = opts
	return &AbuseReportUpsertBulk{
		create: arcb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (arcb *AbuseReportCreateBulk) OnConflictColumns(columns ...string) *AbuseReportUpsertBulk {
	arcb.conflict = append(arcb.conflict, sql.ConflictColumns(columns...))
	return &AbuseReportUpsertBulk{
		create: arcb,
	}
}

// AbuseReportUpsertBulk is the builder for "upsert"-ing
// a bulk of AbuseReport nodes.
type AbuseReportUpsertBulk struct {
	create *AbuseReportCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *AbuseReportUpsertBulk) UpdateNewValues() *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(abusereport.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.AbuseReport.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *AbuseReportUpsertBulk) Ignore() *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *AbuseReportUpsertBulk) DoNothing() *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the AbuseReportCreateBulk.OnConflict
// documentation for more info.
func (u *AbuseReportUpsertBulk) Update(set func(*AbuseReportUpsert)) *AbuseReportUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&AbuseReportUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *AbuseReportUpsertBulk) SetUpdatedAt(v time.Time) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateUpdatedAt() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *AbuseReportUpsertBulk) SetDeletedAt(v time.Time) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateDeletedAt() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *AbuseReportUpsertBulk) ClearDeletedAt() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearDeletedAt()
	})
}

// SetFolderPath sets the "folder_path" field.
func (u *AbuseReportUpsertBulk) SetFolderPath(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetFolderPath(v)
	})
}

// UpdateFolderPath sets the "folder_path" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateFolderPath() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateFolderPath()
	})
}

// ClearFolderPath clears the value of the "folder_path" field.
func (u *AbuseReportUpsertBulk) ClearFolderPath() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearFolderPath()
	})
}

// SetReason sets the "reason" field.
func (u *AbuseReportUpsertBulk) SetReason(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReason(v)
	})
}

// UpdateReason sets the "reason" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateReason() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReason()
	})
}

// ClearReason clears the value of the "reason" field.
func (u *AbuseReportUpsertBulk) ClearReason() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReason()
	})
}

// SetDescription sets the "description" field.
func (u *AbuseReportUpsertBulk) SetDescription(v string) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateDescription() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *AbuseReportUpsertBulk) ClearDescription() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearDescription()
	})
}

// SetStatus sets the "status" field.
func (u *AbuseReportUpsertBulk) SetStatus(v abusereport.Status) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateStatus() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateStatus()
	})
}

// SetRawContent sets the "raw_content" field.
func (u *AbuseReportUpsertBulk) SetRawContent(v *types.AuditContent) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetRawContent(v)
	})
}

// UpdateRawContent sets the "raw_content" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateRawContent() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateRawContent()
	})
}

// ClearRawContent clears the value of the "raw_content" field.
func (u *AbuseReportUpsertBulk) ClearRawContent() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearRawContent()
	})
}

// SetReporterUser sets the "reporter_user" field.
func (u *AbuseReportUpsertBulk) SetReporterUser(v int) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReporterUser(v)
	})
}

// UpdateReporterUser sets the "reporter_user" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateReporterUser() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReporterUser()
	})
}

// ClearReporterUser clears the value of the "reporter_user" field.
func (u *AbuseReportUpsertBulk) ClearReporterUser() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReporterUser()
	})
}

// SetReportedUser sets the "reported_user" field.
func (u *AbuseReportUpsertBulk) SetReportedUser(v int) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetReportedUser(v)
	})
}

// UpdateReportedUser sets the "reported_user" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateReportedUser() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateReportedUser()
	})
}

// ClearReportedUser clears the value of the "reported_user" field.
func (u *AbuseReportUpsertBulk) ClearReportedUser() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearReportedUser()
	})
}

// SetShareReports sets the "share_reports" field.
func (u *AbuseReportUpsertBulk) SetShareReports(v int) *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.SetShareReports(v)
	})
}

// UpdateShareReports sets the "share_reports" field to the value that was provided on create.
func (u *AbuseReportUpsertBulk) UpdateShareReports() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.UpdateShareReports()
	})
}

// ClearShareReports clears the value of the "share_reports" field.
func (u *AbuseReportUpsertBulk) ClearShareReports() *AbuseReportUpsertBulk {
	return u.Update(func(s *AbuseReportUpsert) {
		s.ClearShareReports()
	})
}

// Exec executes the query.
func (u *AbuseReportUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the AbuseReportCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for AbuseReportCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *AbuseReportUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
