// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/abusereport"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// AbuseReport is the model entity for the AbuseReport schema.
type AbuseReport struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// FolderPath holds the value of the "folder_path" field.
	FolderPath string `json:"folder_path,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason string `json:"reason,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status abusereport.Status `json:"status,omitempty"`
	// RawContent holds the value of the "raw_content" field.
	RawContent *types.AuditContent `json:"raw_content,omitempty"`
	// ReporterUser holds the value of the "reporter_user" field.
	ReporterUser int `json:"reporter_user,omitempty"`
	// ReportedUser holds the value of the "reported_user" field.
	ReportedUser int `json:"reported_user,omitempty"`
	// ShareReports holds the value of the "share_reports" field.
	ShareReports int `json:"share_reports,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AbuseReportQuery when eager-loading is set.
	Edges        AbuseReportEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AbuseReportEdges holds the relations/edges for other nodes in the graph.
type AbuseReportEdges struct {
	// Reporter holds the value of the reporter edge.
	Reporter *User `json:"reporter,omitempty"`
	// Reported holds the value of the reported edge.
	Reported *User `json:"reported,omitempty"`
	// Share holds the value of the share edge.
	Share *Share `json:"share,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ReporterOrErr returns the Reporter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AbuseReportEdges) ReporterOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.Reporter == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Reporter, nil
	}
	return nil, &NotLoadedError{edge: "reporter"}
}

// ReportedOrErr returns the Reported value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AbuseReportEdges) ReportedOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.Reported == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Reported, nil
	}
	return nil, &NotLoadedError{edge: "reported"}
}

// ShareOrErr returns the Share value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AbuseReportEdges) ShareOrErr() (*Share, error) {
	if e.loadedTypes[2] {
		if e.Share == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: share.Label}
		}
		return e.Share, nil
	}
	return nil, &NotLoadedError{edge: "share"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AbuseReport) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case abusereport.FieldRawContent:
			values[i] = new([]byte)
		case abusereport.FieldID, abusereport.FieldReporterUser, abusereport.FieldReportedUser, abusereport.FieldShareReports:
			values[i] = new(sql.NullInt64)
		case abusereport.FieldFolderPath, abusereport.FieldReason, abusereport.FieldDescription, abusereport.FieldStatus:
			values[i] = new(sql.NullString)
		case abusereport.FieldCreatedAt, abusereport.FieldUpdatedAt, abusereport.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AbuseReport fields.
func (ar *AbuseReport) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case abusereport.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			ar.ID = int(value.Int64)
		case abusereport.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ar.CreatedAt = value.Time
			}
		case abusereport.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ar.UpdatedAt = value.Time
			}
		case abusereport.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				ar.DeletedAt = new(time.Time)
				*ar.DeletedAt = value.Time
			}
		case abusereport.FieldFolderPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field folder_path", values[i])
			} else if value.Valid {
				ar.FolderPath = value.String
			}
		case abusereport.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				ar.Reason = value.String
			}
		case abusereport.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				ar.Description = value.String
			}
		case abusereport.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				ar.Status = abusereport.Status(value.String)
			}
		case abusereport.FieldRawContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field raw_content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &ar.RawContent); err != nil {
					return fmt.Errorf("unmarshal field raw_content: %w", err)
				}
			}
		case abusereport.FieldReporterUser:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reporter_user", values[i])
			} else if value.Valid {
				ar.ReporterUser = int(value.Int64)
			}
		case abusereport.FieldReportedUser:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reported_user", values[i])
			} else if value.Valid {
				ar.ReportedUser = int(value.Int64)
			}
		case abusereport.FieldShareReports:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_reports", values[i])
			} else if value.Valid {
				ar.ShareReports = int(value.Int64)
			}
		default:
			ar.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AbuseReport.
// This includes values selected through modifiers, order, etc.
func (ar *AbuseReport) Value(name string) (ent.Value, error) {
	return ar.selectValues.Get(name)
}

// QueryReporter queries the "reporter" edge of the AbuseReport entity.
func (ar *AbuseReport) QueryReporter() *UserQuery {
	return NewAbuseReportClient(ar.config).QueryReporter(ar)
}

// QueryReported queries the "reported" edge of the AbuseReport entity.
func (ar *AbuseReport) QueryReported() *UserQuery {
	return NewAbuseReportClient(ar.config).QueryReported(ar)
}

// QueryShare queries the "share" edge of the AbuseReport entity.
func (ar *AbuseReport) QueryShare() *ShareQuery {
	return NewAbuseReportClient(ar.config).QueryShare(ar)
}

// Update returns a builder for updating this AbuseReport.
// Note that you need to call AbuseReport.Unwrap() before calling this method if this AbuseReport
// was returned from a transaction, and the transaction was committed or rolled back.
func (ar *AbuseReport) Update() *AbuseReportUpdateOne {
	return NewAbuseReportClient(ar.config).UpdateOne(ar)
}

// Unwrap unwraps the AbuseReport entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ar *AbuseReport) Unwrap() *AbuseReport {
	_tx, ok := ar.config.driver.(*txDriver)
	if !ok {
		panic("ent: AbuseReport is not a transactional entity")
	}
	ar.config.driver = _tx.drv
	return ar
}

// String implements the fmt.Stringer.
func (ar *AbuseReport) String() string {
	var builder strings.Builder
	builder.WriteString("AbuseReport(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ar.ID))
	builder.WriteString("created_at=")
	builder.WriteString(ar.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ar.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := ar.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("folder_path=")
	builder.WriteString(ar.FolderPath)
	builder.WriteString(", ")
	builder.WriteString("reason=")
	builder.WriteString(ar.Reason)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(ar.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", ar.Status))
	builder.WriteString(", ")
	builder.WriteString("raw_content=")
	builder.WriteString(fmt.Sprintf("%v", ar.RawContent))
	builder.WriteString(", ")
	builder.WriteString("reporter_user=")
	builder.WriteString(fmt.Sprintf("%v", ar.ReporterUser))
	builder.WriteString(", ")
	builder.WriteString("reported_user=")
	builder.WriteString(fmt.Sprintf("%v", ar.ReportedUser))
	builder.WriteString(", ")
	builder.WriteString("share_reports=")
	builder.WriteString(fmt.Sprintf("%v", ar.ShareReports))
	builder.WriteByte(')')
	return builder.String()
}

// SetReporter manually set the edge as loaded state.
func (e *AbuseReport) SetReporter(v *User) {
	e.Edges.Reporter = v
	e.Edges.loadedTypes[0] = true
}

// SetReported manually set the edge as loaded state.
func (e *AbuseReport) SetReported(v *User) {
	e.Edges.Reported = v
	e.Edges.loadedTypes[1] = true
}

// SetShare manually set the edge as loaded state.
func (e *AbuseReport) SetShare(v *Share) {
	e.Edges.Share = v
	e.Edges.loadedTypes[2] = true
}

// AbuseReports is a parsable slice of AbuseReport.
type AbuseReports []*AbuseReport
