// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/entity"
	"github.com/cloudreve/Cloudreve/v4/ent/event"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (eu *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetUpdatedAt sets the "updated_at" field.
func (eu *EventUpdate) SetUpdatedAt(t time.Time) *EventUpdate {
	eu.mutation.SetUpdatedAt(t)
	return eu
}

// SetDeletedAt sets the "deleted_at" field.
func (eu *EventUpdate) SetDeletedAt(t time.Time) *EventUpdate {
	eu.mutation.SetDeletedAt(t)
	return eu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (eu *EventUpdate) SetNillableDeletedAt(t *time.Time) *EventUpdate {
	if t != nil {
		eu.SetDeletedAt(*t)
	}
	return eu
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (eu *EventUpdate) ClearDeletedAt() *EventUpdate {
	eu.mutation.ClearDeletedAt()
	return eu
}

// SetType sets the "type" field.
func (eu *EventUpdate) SetType(i int) *EventUpdate {
	eu.mutation.ResetType()
	eu.mutation.SetType(i)
	return eu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (eu *EventUpdate) SetNillableType(i *int) *EventUpdate {
	if i != nil {
		eu.SetType(*i)
	}
	return eu
}

// AddType adds i to the "type" field.
func (eu *EventUpdate) AddType(i int) *EventUpdate {
	eu.mutation.AddType(i)
	return eu
}

// SetCorrelationID sets the "correlation_id" field.
func (eu *EventUpdate) SetCorrelationID(s string) *EventUpdate {
	eu.mutation.SetCorrelationID(s)
	return eu
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (eu *EventUpdate) SetNillableCorrelationID(s *string) *EventUpdate {
	if s != nil {
		eu.SetCorrelationID(*s)
	}
	return eu
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (eu *EventUpdate) ClearCorrelationID() *EventUpdate {
	eu.mutation.ClearCorrelationID()
	return eu
}

// SetIP sets the "ip" field.
func (eu *EventUpdate) SetIP(s string) *EventUpdate {
	eu.mutation.SetIP(s)
	return eu
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (eu *EventUpdate) SetNillableIP(s *string) *EventUpdate {
	if s != nil {
		eu.SetIP(*s)
	}
	return eu
}

// ClearIP clears the value of the "ip" field.
func (eu *EventUpdate) ClearIP() *EventUpdate {
	eu.mutation.ClearIP()
	return eu
}

// SetUserAgent sets the "user_agent" field.
func (eu *EventUpdate) SetUserAgent(s string) *EventUpdate {
	eu.mutation.SetUserAgent(s)
	return eu
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (eu *EventUpdate) SetNillableUserAgent(s *string) *EventUpdate {
	if s != nil {
		eu.SetUserAgent(*s)
	}
	return eu
}

// ClearUserAgent clears the value of the "user_agent" field.
func (eu *EventUpdate) ClearUserAgent() *EventUpdate {
	eu.mutation.ClearUserAgent()
	return eu
}

// SetContent sets the "content" field.
func (eu *EventUpdate) SetContent(tc *types.AuditContent) *EventUpdate {
	eu.mutation.SetContent(tc)
	return eu
}

// ClearContent clears the value of the "content" field.
func (eu *EventUpdate) ClearContent() *EventUpdate {
	eu.mutation.ClearContent()
	return eu
}

// SetUserEvents sets the "user_events" field.
func (eu *EventUpdate) SetUserEvents(i int) *EventUpdate {
	eu.mutation.SetUserEvents(i)
	return eu
}

// SetNillableUserEvents sets the "user_events" field if the given value is not nil.
func (eu *EventUpdate) SetNillableUserEvents(i *int) *EventUpdate {
	if i != nil {
		eu.SetUserEvents(*i)
	}
	return eu
}

// ClearUserEvents clears the value of the "user_events" field.
func (eu *EventUpdate) ClearUserEvents() *EventUpdate {
	eu.mutation.ClearUserEvents()
	return eu
}

// SetFileEvents sets the "file_events" field.
func (eu *EventUpdate) SetFileEvents(i int) *EventUpdate {
	eu.mutation.SetFileEvents(i)
	return eu
}

// SetNillableFileEvents sets the "file_events" field if the given value is not nil.
func (eu *EventUpdate) SetNillableFileEvents(i *int) *EventUpdate {
	if i != nil {
		eu.SetFileEvents(*i)
	}
	return eu
}

// ClearFileEvents clears the value of the "file_events" field.
func (eu *EventUpdate) ClearFileEvents() *EventUpdate {
	eu.mutation.ClearFileEvents()
	return eu
}

// SetEntityEvents sets the "entity_events" field.
func (eu *EventUpdate) SetEntityEvents(i int) *EventUpdate {
	eu.mutation.SetEntityEvents(i)
	return eu
}

// SetNillableEntityEvents sets the "entity_events" field if the given value is not nil.
func (eu *EventUpdate) SetNillableEntityEvents(i *int) *EventUpdate {
	if i != nil {
		eu.SetEntityEvents(*i)
	}
	return eu
}

// ClearEntityEvents clears the value of the "entity_events" field.
func (eu *EventUpdate) ClearEntityEvents() *EventUpdate {
	eu.mutation.ClearEntityEvents()
	return eu
}

// SetShareEvents sets the "share_events" field.
func (eu *EventUpdate) SetShareEvents(i int) *EventUpdate {
	eu.mutation.SetShareEvents(i)
	return eu
}

// SetNillableShareEvents sets the "share_events" field if the given value is not nil.
func (eu *EventUpdate) SetNillableShareEvents(i *int) *EventUpdate {
	if i != nil {
		eu.SetShareEvents(*i)
	}
	return eu
}

// ClearShareEvents clears the value of the "share_events" field.
func (eu *EventUpdate) ClearShareEvents() *EventUpdate {
	eu.mutation.ClearShareEvents()
	return eu
}

// SetUserID sets the "user" edge to the User entity by ID.
func (eu *EventUpdate) SetUserID(id int) *EventUpdate {
	eu.mutation.SetUserID(id)
	return eu
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (eu *EventUpdate) SetNillableUserID(id *int) *EventUpdate {
	if id != nil {
		eu = eu.SetUserID(*id)
	}
	return eu
}

// SetUser sets the "user" edge to the User entity.
func (eu *EventUpdate) SetUser(u *User) *EventUpdate {
	return eu.SetUserID(u.ID)
}

// SetFileID sets the "file" edge to the File entity by ID.
func (eu *EventUpdate) SetFileID(id int) *EventUpdate {
	eu.mutation.SetFileID(id)
	return eu
}

// SetNillableFileID sets the "file" edge to the File entity by ID if the given value is not nil.
func (eu *EventUpdate) SetNillableFileID(id *int) *EventUpdate {
	if id != nil {
		eu = eu.SetFileID(*id)
	}
	return eu
}

// SetFile sets the "file" edge to the File entity.
func (eu *EventUpdate) SetFile(f *File) *EventUpdate {
	return eu.SetFileID(f.ID)
}

// SetEntityID sets the "entity" edge to the Entity entity by ID.
func (eu *EventUpdate) SetEntityID(id int) *EventUpdate {
	eu.mutation.SetEntityID(id)
	return eu
}

// SetNillableEntityID sets the "entity" edge to the Entity entity by ID if the given value is not nil.
func (eu *EventUpdate) SetNillableEntityID(id *int) *EventUpdate {
	if id != nil {
		eu = eu.SetEntityID(*id)
	}
	return eu
}

// SetEntity sets the "entity" edge to the Entity entity.
func (eu *EventUpdate) SetEntity(e *Entity) *EventUpdate {
	return eu.SetEntityID(e.ID)
}

// SetShareID sets the "share" edge to the Share entity by ID.
func (eu *EventUpdate) SetShareID(id int) *EventUpdate {
	eu.mutation.SetShareID(id)
	return eu
}

// SetNillableShareID sets the "share" edge to the Share entity by ID if the given value is not nil.
func (eu *EventUpdate) SetNillableShareID(id *int) *EventUpdate {
	if id != nil {
		eu = eu.SetShareID(*id)
	}
	return eu
}

// SetShare sets the "share" edge to the Share entity.
func (eu *EventUpdate) SetShare(s *Share) *EventUpdate {
	return eu.SetShareID(s.ID)
}

// Mutation returns the EventMutation object of the builder.
func (eu *EventUpdate) Mutation() *EventMutation {
	return eu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (eu *EventUpdate) ClearUser() *EventUpdate {
	eu.mutation.ClearUser()
	return eu
}

// ClearFile clears the "file" edge to the File entity.
func (eu *EventUpdate) ClearFile() *EventUpdate {
	eu.mutation.ClearFile()
	return eu
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (eu *EventUpdate) ClearEntity() *EventUpdate {
	eu.mutation.ClearEntity()
	return eu
}

// ClearShare clears the "share" edge to the Share entity.
func (eu *EventUpdate) ClearShare() *EventUpdate {
	eu.mutation.ClearShare()
	return eu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EventUpdate) Save(ctx context.Context) (int, error) {
	if err := eu.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, eu.sqlSave, eu.mutation, eu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EventUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EventUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (eu *EventUpdate) defaults() error {
	if _, ok := eu.mutation.UpdatedAt(); !ok {
		if event.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := event.UpdateDefaultUpdatedAt()
		eu.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (eu *EventUpdate) check() error {
	if v, ok := eu.mutation.CorrelationID(); ok {
		if err := event.CorrelationIDValidator(v); err != nil {
			return &ValidationError{Name: "correlation_id", err: fmt.Errorf(`ent: validator failed for field "Event.correlation_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.IP(); ok {
		if err := event.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Event.ip": %w`, err)}
		}
	}
	if v, ok := eu.mutation.UserAgent(); ok {
		if err := event.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Event.user_agent": %w`, err)}
		}
	}
	return nil
}

func (eu *EventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := eu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := eu.mutation.DeletedAt(); ok {
		_spec.SetField(event.FieldDeletedAt, field.TypeTime, value)
	}
	if eu.mutation.DeletedAtCleared() {
		_spec.ClearField(event.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := eu.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeInt, value)
	}
	if value, ok := eu.mutation.AddedType(); ok {
		_spec.AddField(event.FieldType, field.TypeInt, value)
	}
	if value, ok := eu.mutation.CorrelationID(); ok {
		_spec.SetField(event.FieldCorrelationID, field.TypeString, value)
	}
	if eu.mutation.CorrelationIDCleared() {
		_spec.ClearField(event.FieldCorrelationID, field.TypeString)
	}
	if value, ok := eu.mutation.IP(); ok {
		_spec.SetField(event.FieldIP, field.TypeString, value)
	}
	if eu.mutation.IPCleared() {
		_spec.ClearField(event.FieldIP, field.TypeString)
	}
	if value, ok := eu.mutation.UserAgent(); ok {
		_spec.SetField(event.FieldUserAgent, field.TypeString, value)
	}
	if eu.mutation.UserAgentCleared() {
		_spec.ClearField(event.FieldUserAgent, field.TypeString)
	}
	if value, ok := eu.mutation.Content(); ok {
		_spec.SetField(event.FieldContent, field.TypeJSON, value)
	}
	if eu.mutation.ContentCleared() {
		_spec.ClearField(event.FieldContent, field.TypeJSON)
	}
	if eu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UserTable,
			Columns: []string{event.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UserTable,
			Columns: []string{event.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.FileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.FileTable,
			Columns: []string{event.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.FileTable,
			Columns: []string{event.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EntityTable,
			Columns: []string{event.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EntityTable,
			Columns: []string{event.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if eu.mutation.ShareCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ShareTable,
			Columns: []string{event.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := eu.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ShareTable,
			Columns: []string{event.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	eu.mutation.done = true
	return n, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (euo *EventUpdateOne) SetUpdatedAt(t time.Time) *EventUpdateOne {
	euo.mutation.SetUpdatedAt(t)
	return euo
}

// SetDeletedAt sets the "deleted_at" field.
func (euo *EventUpdateOne) SetDeletedAt(t time.Time) *EventUpdateOne {
	euo.mutation.SetDeletedAt(t)
	return euo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableDeletedAt(t *time.Time) *EventUpdateOne {
	if t != nil {
		euo.SetDeletedAt(*t)
	}
	return euo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (euo *EventUpdateOne) ClearDeletedAt() *EventUpdateOne {
	euo.mutation.ClearDeletedAt()
	return euo
}

// SetType sets the "type" field.
func (euo *EventUpdateOne) SetType(i int) *EventUpdateOne {
	euo.mutation.ResetType()
	euo.mutation.SetType(i)
	return euo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableType(i *int) *EventUpdateOne {
	if i != nil {
		euo.SetType(*i)
	}
	return euo
}

// AddType adds i to the "type" field.
func (euo *EventUpdateOne) AddType(i int) *EventUpdateOne {
	euo.mutation.AddType(i)
	return euo
}

// SetCorrelationID sets the "correlation_id" field.
func (euo *EventUpdateOne) SetCorrelationID(s string) *EventUpdateOne {
	euo.mutation.SetCorrelationID(s)
	return euo
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableCorrelationID(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetCorrelationID(*s)
	}
	return euo
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (euo *EventUpdateOne) ClearCorrelationID() *EventUpdateOne {
	euo.mutation.ClearCorrelationID()
	return euo
}

// SetIP sets the "ip" field.
func (euo *EventUpdateOne) SetIP(s string) *EventUpdateOne {
	euo.mutation.SetIP(s)
	return euo
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableIP(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetIP(*s)
	}
	return euo
}

// ClearIP clears the value of the "ip" field.
func (euo *EventUpdateOne) ClearIP() *EventUpdateOne {
	euo.mutation.ClearIP()
	return euo
}

// SetUserAgent sets the "user_agent" field.
func (euo *EventUpdateOne) SetUserAgent(s string) *EventUpdateOne {
	euo.mutation.SetUserAgent(s)
	return euo
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableUserAgent(s *string) *EventUpdateOne {
	if s != nil {
		euo.SetUserAgent(*s)
	}
	return euo
}

// ClearUserAgent clears the value of the "user_agent" field.
func (euo *EventUpdateOne) ClearUserAgent() *EventUpdateOne {
	euo.mutation.ClearUserAgent()
	return euo
}

// SetContent sets the "content" field.
func (euo *EventUpdateOne) SetContent(tc *types.AuditContent) *EventUpdateOne {
	euo.mutation.SetContent(tc)
	return euo
}

// ClearContent clears the value of the "content" field.
func (euo *EventUpdateOne) ClearContent() *EventUpdateOne {
	euo.mutation.ClearContent()
	return euo
}

// SetUserEvents sets the "user_events" field.
func (euo *EventUpdateOne) SetUserEvents(i int) *EventUpdateOne {
	euo.mutation.SetUserEvents(i)
	return euo
}

// SetNillableUserEvents sets the "user_events" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableUserEvents(i *int) *EventUpdateOne {
	if i != nil {
		euo.SetUserEvents(*i)
	}
	return euo
}

// ClearUserEvents clears the value of the "user_events" field.
func (euo *EventUpdateOne) ClearUserEvents() *EventUpdateOne {
	euo.mutation.ClearUserEvents()
	return euo
}

// SetFileEvents sets the "file_events" field.
func (euo *EventUpdateOne) SetFileEvents(i int) *EventUpdateOne {
	euo.mutation.SetFileEvents(i)
	return euo
}

// SetNillableFileEvents sets the "file_events" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableFileEvents(i *int) *EventUpdateOne {
	if i != nil {
		euo.SetFileEvents(*i)
	}
	return euo
}

// ClearFileEvents clears the value of the "file_events" field.
func (euo *EventUpdateOne) ClearFileEvents() *EventUpdateOne {
	euo.mutation.ClearFileEvents()
	return euo
}

// SetEntityEvents sets the "entity_events" field.
func (euo *EventUpdateOne) SetEntityEvents(i int) *EventUpdateOne {
	euo.mutation.SetEntityEvents(i)
	return euo
}

// SetNillableEntityEvents sets the "entity_events" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableEntityEvents(i *int) *EventUpdateOne {
	if i != nil {
		euo.SetEntityEvents(*i)
	}
	return euo
}

// ClearEntityEvents clears the value of the "entity_events" field.
func (euo *EventUpdateOne) ClearEntityEvents() *EventUpdateOne {
	euo.mutation.ClearEntityEvents()
	return euo
}

// SetShareEvents sets the "share_events" field.
func (euo *EventUpdateOne) SetShareEvents(i int) *EventUpdateOne {
	euo.mutation.SetShareEvents(i)
	return euo
}

// SetNillableShareEvents sets the "share_events" field if the given value is not nil.
func (euo *EventUpdateOne) SetNillableShareEvents(i *int) *EventUpdateOne {
	if i != nil {
		euo.SetShareEvents(*i)
	}
	return euo
}

// ClearShareEvents clears the value of the "share_events" field.
func (euo *EventUpdateOne) ClearShareEvents() *EventUpdateOne {
	euo.mutation.ClearShareEvents()
	return euo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (euo *EventUpdateOne) SetUserID(id int) *EventUpdateOne {
	euo.mutation.SetUserID(id)
	return euo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (euo *EventUpdateOne) SetNillableUserID(id *int) *EventUpdateOne {
	if id != nil {
		euo = euo.SetUserID(*id)
	}
	return euo
}

// SetUser sets the "user" edge to the User entity.
func (euo *EventUpdateOne) SetUser(u *User) *EventUpdateOne {
	return euo.SetUserID(u.ID)
}

// SetFileID sets the "file" edge to the File entity by ID.
func (euo *EventUpdateOne) SetFileID(id int) *EventUpdateOne {
	euo.mutation.SetFileID(id)
	return euo
}

// SetNillableFileID sets the "file" edge to the File entity by ID if the given value is not nil.
func (euo *EventUpdateOne) SetNillableFileID(id *int) *EventUpdateOne {
	if id != nil {
		euo = euo.SetFileID(*id)
	}
	return euo
}

// SetFile sets the "file" edge to the File entity.
func (euo *EventUpdateOne) SetFile(f *File) *EventUpdateOne {
	return euo.SetFileID(f.ID)
}

// SetEntityID sets the "entity" edge to the Entity entity by ID.
func (euo *EventUpdateOne) SetEntityID(id int) *EventUpdateOne {
	euo.mutation.SetEntityID(id)
	return euo
}

// SetNillableEntityID sets the "entity" edge to the Entity entity by ID if the given value is not nil.
func (euo *EventUpdateOne) SetNillableEntityID(id *int) *EventUpdateOne {
	if id != nil {
		euo = euo.SetEntityID(*id)
	}
	return euo
}

// SetEntity sets the "entity" edge to the Entity entity.
func (euo *EventUpdateOne) SetEntity(e *Entity) *EventUpdateOne {
	return euo.SetEntityID(e.ID)
}

// SetShareID sets the "share" edge to the Share entity by ID.
func (euo *EventUpdateOne) SetShareID(id int) *EventUpdateOne {
	euo.mutation.SetShareID(id)
	return euo
}

// SetNillableShareID sets the "share" edge to the Share entity by ID if the given value is not nil.
func (euo *EventUpdateOne) SetNillableShareID(id *int) *EventUpdateOne {
	if id != nil {
		euo = euo.SetShareID(*id)
	}
	return euo
}

// SetShare sets the "share" edge to the Share entity.
func (euo *EventUpdateOne) SetShare(s *Share) *EventUpdateOne {
	return euo.SetShareID(s.ID)
}

// Mutation returns the EventMutation object of the builder.
func (euo *EventUpdateOne) Mutation() *EventMutation {
	return euo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (euo *EventUpdateOne) ClearUser() *EventUpdateOne {
	euo.mutation.ClearUser()
	return euo
}

// ClearFile clears the "file" edge to the File entity.
func (euo *EventUpdateOne) ClearFile() *EventUpdateOne {
	euo.mutation.ClearFile()
	return euo
}

// ClearEntity clears the "entity" edge to the Entity entity.
func (euo *EventUpdateOne) ClearEntity() *EventUpdateOne {
	euo.mutation.ClearEntity()
	return euo
}

// ClearShare clears the "share" edge to the Share entity.
func (euo *EventUpdateOne) ClearShare() *EventUpdateOne {
	euo.mutation.ClearShare()
	return euo
}

// Where appends a list predicates to the EventUpdate builder.
func (euo *EventUpdateOne) Where(ps ...predicate.Event) *EventUpdateOne {
	euo.mutation.Where(ps...)
	return euo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Event entity.
func (euo *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	if err := euo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, euo.sqlSave, euo.mutation, euo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EventUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (euo *EventUpdateOne) defaults() error {
	if _, ok := euo.mutation.UpdatedAt(); !ok {
		if event.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := event.UpdateDefaultUpdatedAt()
		euo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (euo *EventUpdateOne) check() error {
	if v, ok := euo.mutation.CorrelationID(); ok {
		if err := event.CorrelationIDValidator(v); err != nil {
			return &ValidationError{Name: "correlation_id", err: fmt.Errorf(`ent: validator failed for field "Event.correlation_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.IP(); ok {
		if err := event.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Event.ip": %w`, err)}
		}
	}
	if v, ok := euo.mutation.UserAgent(); ok {
		if err := event.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Event.user_agent": %w`, err)}
		}
	}
	return nil
}

func (euo *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	if err := euo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(event.Table, event.Columns, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := euo.mutation.DeletedAt(); ok {
		_spec.SetField(event.FieldDeletedAt, field.TypeTime, value)
	}
	if euo.mutation.DeletedAtCleared() {
		_spec.ClearField(event.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := euo.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeInt, value)
	}
	if value, ok := euo.mutation.AddedType(); ok {
		_spec.AddField(event.FieldType, field.TypeInt, value)
	}
	if value, ok := euo.mutation.CorrelationID(); ok {
		_spec.SetField(event.FieldCorrelationID, field.TypeString, value)
	}
	if euo.mutation.CorrelationIDCleared() {
		_spec.ClearField(event.FieldCorrelationID, field.TypeString)
	}
	if value, ok := euo.mutation.IP(); ok {
		_spec.SetField(event.FieldIP, field.TypeString, value)
	}
	if euo.mutation.IPCleared() {
		_spec.ClearField(event.FieldIP, field.TypeString)
	}
	if value, ok := euo.mutation.UserAgent(); ok {
		_spec.SetField(event.FieldUserAgent, field.TypeString, value)
	}
	if euo.mutation.UserAgentCleared() {
		_spec.ClearField(event.FieldUserAgent, field.TypeString)
	}
	if value, ok := euo.mutation.Content(); ok {
		_spec.SetField(event.FieldContent, field.TypeJSON, value)
	}
	if euo.mutation.ContentCleared() {
		_spec.ClearField(event.FieldContent, field.TypeJSON)
	}
	if euo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UserTable,
			Columns: []string{event.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UserTable,
			Columns: []string{event.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.FileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.FileTable,
			Columns: []string{event.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.FileTable,
			Columns: []string{event.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.EntityCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EntityTable,
			Columns: []string{event.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EntityTable,
			Columns: []string{event.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if euo.mutation.ShareCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ShareTable,
			Columns: []string{event.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := euo.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ShareTable,
			Columns: []string{event.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Event{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	euo.mutation.done = true
	return _node, nil
}
