// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/entity"
	"github.com/cloudreve/Cloudreve/v4/ent/event"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// Event is the model entity for the Event schema.
type Event struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Audit log type, aligned with types.AuditType
	Type int `json:"type,omitempty"`
	// CorrelationID holds the value of the "correlation_id" field.
	CorrelationID string `json:"correlation_id,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// UserAgent holds the value of the "user_agent" field.
	UserAgent string `json:"user_agent,omitempty"`
	// Content holds the value of the "content" field.
	Content *types.AuditContent `json:"content,omitempty"`
	// UserEvents holds the value of the "user_events" field.
	UserEvents int `json:"user_events,omitempty"`
	// FileEvents holds the value of the "file_events" field.
	FileEvents int `json:"file_events,omitempty"`
	// EntityEvents holds the value of the "entity_events" field.
	EntityEvents int `json:"entity_events,omitempty"`
	// ShareEvents holds the value of the "share_events" field.
	ShareEvents int `json:"share_events,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EventQuery when eager-loading is set.
	Edges        EventEdges `json:"edges"`
	selectValues sql.SelectValues
}

// EventEdges holds the relations/edges for other nodes in the graph.
type EventEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// File holds the value of the file edge.
	File *File `json:"file,omitempty"`
	// Entity holds the value of the entity edge.
	Entity *Entity `json:"entity,omitempty"`
	// Share holds the value of the share edge.
	Share *Share `json:"share,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// FileOrErr returns the File value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) FileOrErr() (*File, error) {
	if e.loadedTypes[1] {
		if e.File == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: file.Label}
		}
		return e.File, nil
	}
	return nil, &NotLoadedError{edge: "file"}
}

// EntityOrErr returns the Entity value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) EntityOrErr() (*Entity, error) {
	if e.loadedTypes[2] {
		if e.Entity == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: entity.Label}
		}
		return e.Entity, nil
	}
	return nil, &NotLoadedError{edge: "entity"}
}

// ShareOrErr returns the Share value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EventEdges) ShareOrErr() (*Share, error) {
	if e.loadedTypes[3] {
		if e.Share == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: share.Label}
		}
		return e.Share, nil
	}
	return nil, &NotLoadedError{edge: "share"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Event) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case event.FieldContent:
			values[i] = new([]byte)
		case event.FieldID, event.FieldType, event.FieldUserEvents, event.FieldFileEvents, event.FieldEntityEvents, event.FieldShareEvents:
			values[i] = new(sql.NullInt64)
		case event.FieldCorrelationID, event.FieldIP, event.FieldUserAgent:
			values[i] = new(sql.NullString)
		case event.FieldCreatedAt, event.FieldUpdatedAt, event.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Event fields.
func (e *Event) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case event.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			e.ID = int(value.Int64)
		case event.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				e.CreatedAt = value.Time
			}
		case event.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				e.UpdatedAt = value.Time
			}
		case event.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				e.DeletedAt = new(time.Time)
				*e.DeletedAt = value.Time
			}
		case event.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				e.Type = int(value.Int64)
			}
		case event.FieldCorrelationID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field correlation_id", values[i])
			} else if value.Valid {
				e.CorrelationID = value.String
			}
		case event.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				e.IP = value.String
			}
		case event.FieldUserAgent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_agent", values[i])
			} else if value.Valid {
				e.UserAgent = value.String
			}
		case event.FieldContent:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &e.Content); err != nil {
					return fmt.Errorf("unmarshal field content: %w", err)
				}
			}
		case event.FieldUserEvents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_events", values[i])
			} else if value.Valid {
				e.UserEvents = int(value.Int64)
			}
		case event.FieldFileEvents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field file_events", values[i])
			} else if value.Valid {
				e.FileEvents = int(value.Int64)
			}
		case event.FieldEntityEvents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field entity_events", values[i])
			} else if value.Valid {
				e.EntityEvents = int(value.Int64)
			}
		case event.FieldShareEvents:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field share_events", values[i])
			} else if value.Valid {
				e.ShareEvents = int(value.Int64)
			}
		default:
			e.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Event.
// This includes values selected through modifiers, order, etc.
func (e *Event) Value(name string) (ent.Value, error) {
	return e.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Event entity.
func (e *Event) QueryUser() *UserQuery {
	return NewEventClient(e.config).QueryUser(e)
}

// QueryFile queries the "file" edge of the Event entity.
func (e *Event) QueryFile() *FileQuery {
	return NewEventClient(e.config).QueryFile(e)
}

// QueryEntity queries the "entity" edge of the Event entity.
func (e *Event) QueryEntity() *EntityQuery {
	return NewEventClient(e.config).QueryEntity(e)
}

// QueryShare queries the "share" edge of the Event entity.
func (e *Event) QueryShare() *ShareQuery {
	return NewEventClient(e.config).QueryShare(e)
}

// Update returns a builder for updating this Event.
// Note that you need to call Event.Unwrap() before calling this method if this Event
// was returned from a transaction, and the transaction was committed or rolled back.
func (e *Event) Update() *EventUpdateOne {
	return NewEventClient(e.config).UpdateOne(e)
}

// Unwrap unwraps the Event entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (e *Event) Unwrap() *Event {
	_tx, ok := e.config.driver.(*txDriver)
	if !ok {
		panic("ent: Event is not a transactional entity")
	}
	e.config.driver = _tx.drv
	return e
}

// String implements the fmt.Stringer.
func (e *Event) String() string {
	var builder strings.Builder
	builder.WriteString("Event(")
	builder.WriteString(fmt.Sprintf("id=%v, ", e.ID))
	builder.WriteString("created_at=")
	builder.WriteString(e.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(e.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := e.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", e.Type))
	builder.WriteString(", ")
	builder.WriteString("correlation_id=")
	builder.WriteString(e.CorrelationID)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(e.IP)
	builder.WriteString(", ")
	builder.WriteString("user_agent=")
	builder.WriteString(e.UserAgent)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(fmt.Sprintf("%v", e.Content))
	builder.WriteString(", ")
	builder.WriteString("user_events=")
	builder.WriteString(fmt.Sprintf("%v", e.UserEvents))
	builder.WriteString(", ")
	builder.WriteString("file_events=")
	builder.WriteString(fmt.Sprintf("%v", e.FileEvents))
	builder.WriteString(", ")
	builder.WriteString("entity_events=")
	builder.WriteString(fmt.Sprintf("%v", e.EntityEvents))
	builder.WriteString(", ")
	builder.WriteString("share_events=")
	builder.WriteString(fmt.Sprintf("%v", e.ShareEvents))
	builder.WriteByte(')')
	return builder.String()
}

// SetUser manually set the edge as loaded state.
func (e *Event) SetUser(v *User) {
	e.Edges.User = v
	e.Edges.loadedTypes[0] = true
}

// SetFile manually set the edge as loaded state.
func (e *Event) SetFile(v *File) {
	e.Edges.File = v
	e.Edges.loadedTypes[1] = true
}

// SetEntity manually set the edge as loaded state.
func (e *Event) SetEntity(v *Entity) {
	e.Edges.Entity = v
	e.Edges.loadedTypes[2] = true
}

// SetShare manually set the edge as loaded state.
func (e *Event) SetShare(v *Share) {
	e.Edges.Share = v
	e.Edges.loadedTypes[3] = true
}

// Events is a parsable slice of Event.
type Events []*Event
