// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/entity"
	"github.com/cloudreve/Cloudreve/v4/ent/event"
	"github.com/cloudreve/Cloudreve/v4/ent/file"
	"github.com/cloudreve/Cloudreve/v4/ent/share"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// EventCreate is the builder for creating a Event entity.
type EventCreate struct {
	config
	mutation *EventMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (ec *EventCreate) SetCreatedAt(t time.Time) *EventCreate {
	ec.mutation.SetCreatedAt(t)
	return ec
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ec *EventCreate) SetNillableCreatedAt(t *time.Time) *EventCreate {
	if t != nil {
		ec.SetCreatedAt(*t)
	}
	return ec
}

// SetUpdatedAt sets the "updated_at" field.
func (ec *EventCreate) SetUpdatedAt(t time.Time) *EventCreate {
	ec.mutation.SetUpdatedAt(t)
	return ec
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ec *EventCreate) SetNillableUpdatedAt(t *time.Time) *EventCreate {
	if t != nil {
		ec.SetUpdatedAt(*t)
	}
	return ec
}

// SetDeletedAt sets the "deleted_at" field.
func (ec *EventCreate) SetDeletedAt(t time.Time) *EventCreate {
	ec.mutation.SetDeletedAt(t)
	return ec
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ec *EventCreate) SetNillableDeletedAt(t *time.Time) *EventCreate {
	if t != nil {
		ec.SetDeletedAt(*t)
	}
	return ec
}

// SetType sets the "type" field.
func (ec *EventCreate) SetType(i int) *EventCreate {
	ec.mutation.SetType(i)
	return ec
}

// SetCorrelationID sets the "correlation_id" field.
func (ec *EventCreate) SetCorrelationID(s string) *EventCreate {
	ec.mutation.SetCorrelationID(s)
	return ec
}

// SetNillableCorrelationID sets the "correlation_id" field if the given value is not nil.
func (ec *EventCreate) SetNillableCorrelationID(s *string) *EventCreate {
	if s != nil {
		ec.SetCorrelationID(*s)
	}
	return ec
}

// SetIP sets the "ip" field.
func (ec *EventCreate) SetIP(s string) *EventCreate {
	ec.mutation.SetIP(s)
	return ec
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (ec *EventCreate) SetNillableIP(s *string) *EventCreate {
	if s != nil {
		ec.SetIP(*s)
	}
	return ec
}

// SetUserAgent sets the "user_agent" field.
func (ec *EventCreate) SetUserAgent(s string) *EventCreate {
	ec.mutation.SetUserAgent(s)
	return ec
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (ec *EventCreate) SetNillableUserAgent(s *string) *EventCreate {
	if s != nil {
		ec.SetUserAgent(*s)
	}
	return ec
}

// SetContent sets the "content" field.
func (ec *EventCreate) SetContent(tc *types.AuditContent) *EventCreate {
	ec.mutation.SetContent(tc)
	return ec
}

// SetUserEvents sets the "user_events" field.
func (ec *EventCreate) SetUserEvents(i int) *EventCreate {
	ec.mutation.SetUserEvents(i)
	return ec
}

// SetNillableUserEvents sets the "user_events" field if the given value is not nil.
func (ec *EventCreate) SetNillableUserEvents(i *int) *EventCreate {
	if i != nil {
		ec.SetUserEvents(*i)
	}
	return ec
}

// SetFileEvents sets the "file_events" field.
func (ec *EventCreate) SetFileEvents(i int) *EventCreate {
	ec.mutation.SetFileEvents(i)
	return ec
}

// SetNillableFileEvents sets the "file_events" field if the given value is not nil.
func (ec *EventCreate) SetNillableFileEvents(i *int) *EventCreate {
	if i != nil {
		ec.SetFileEvents(*i)
	}
	return ec
}

// SetEntityEvents sets the "entity_events" field.
func (ec *EventCreate) SetEntityEvents(i int) *EventCreate {
	ec.mutation.SetEntityEvents(i)
	return ec
}

// SetNillableEntityEvents sets the "entity_events" field if the given value is not nil.
func (ec *EventCreate) SetNillableEntityEvents(i *int) *EventCreate {
	if i != nil {
		ec.SetEntityEvents(*i)
	}
	return ec
}

// SetShareEvents sets the "share_events" field.
func (ec *EventCreate) SetShareEvents(i int) *EventCreate {
	ec.mutation.SetShareEvents(i)
	return ec
}

// SetNillableShareEvents sets the "share_events" field if the given value is not nil.
func (ec *EventCreate) SetNillableShareEvents(i *int) *EventCreate {
	if i != nil {
		ec.SetShareEvents(*i)
	}
	return ec
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ec *EventCreate) SetUserID(id int) *EventCreate {
	ec.mutation.SetUserID(id)
	return ec
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (ec *EventCreate) SetNillableUserID(id *int) *EventCreate {
	if id != nil {
		ec = ec.SetUserID(*id)
	}
	return ec
}

// SetUser sets the "user" edge to the User entity.
func (ec *EventCreate) SetUser(u *User) *EventCreate {
	return ec.SetUserID(u.ID)
}

// SetFileID sets the "file" edge to the File entity by ID.
func (ec *EventCreate) SetFileID(id int) *EventCreate {
	ec.mutation.SetFileID(id)
	return ec
}

// SetNillableFileID sets the "file" edge to the File entity by ID if the given value is not nil.
func (ec *EventCreate) SetNillableFileID(id *int) *EventCreate {
	if id != nil {
		ec = ec.SetFileID(*id)
	}
	return ec
}

// SetFile sets the "file" edge to the File entity.
func (ec *EventCreate) SetFile(f *File) *EventCreate {
	return ec.SetFileID(f.ID)
}

// SetEntityID sets the "entity" edge to the Entity entity by ID.
func (ec *EventCreate) SetEntityID(id int) *EventCreate {
	ec.mutation.SetEntityID(id)
	return ec
}

// SetNillableEntityID sets the "entity" edge to the Entity entity by ID if the given value is not nil.
func (ec *EventCreate) SetNillableEntityID(id *int) *EventCreate {
	if id != nil {
		ec = ec.SetEntityID(*id)
	}
	return ec
}

// SetEntity sets the "entity" edge to the Entity entity.
func (ec *EventCreate) SetEntity(e *Entity) *EventCreate {
	return ec.SetEntityID(e.ID)
}

// SetShareID sets the "share" edge to the Share entity by ID.
func (ec *EventCreate) SetShareID(id int) *EventCreate {
	ec.mutation.SetShareID(id)
	return ec
}

// SetNillableShareID sets the "share" edge to the Share entity by ID if the given value is not nil.
func (ec *EventCreate) SetNillableShareID(id *int) *EventCreate {
	if id != nil {
		ec = ec.SetShareID(*id)
	}
	return ec
}

// SetShare sets the "share" edge to the Share entity.
func (ec *EventCreate) SetShare(s *Share) *EventCreate {
	return ec.SetShareID(s.ID)
}

// Mutation returns the EventMutation object of the builder.
func (ec *EventCreate) Mutation() *EventMutation {
	return ec.mutation
}

// Save creates the Event in the database.
func (ec *EventCreate) Save(ctx context.Context) (*Event, error) {
	if err := ec.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ec.sqlSave, ec.mutation, ec.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ec *EventCreate) SaveX(ctx context.Context) *Event {
	v, err := ec.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ec *EventCreate) Exec(ctx context.Context) error {
	_, err := ec.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ec *EventCreate) ExecX(ctx context.Context) {
	if err := ec.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ec *EventCreate) defaults() error {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		if event.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := event.DefaultCreatedAt()
		ec.mutation.SetCreatedAt(v)
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		if event.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized event.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := event.DefaultUpdatedAt()
		ec.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ec *EventCreate) check() error {
	if _, ok := ec.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Event.created_at"`)}
	}
	if _, ok := ec.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Event.updated_at"`)}
	}
	if _, ok := ec.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "Event.type"`)}
	}
	if v, ok := ec.mutation.CorrelationID(); ok {
		if err := event.CorrelationIDValidator(v); err != nil {
			return &ValidationError{Name: "correlation_id", err: fmt.Errorf(`ent: validator failed for field "Event.correlation_id": %w`, err)}
		}
	}
	if v, ok := ec.mutation.IP(); ok {
		if err := event.IPValidator(v); err != nil {
			return &ValidationError{Name: "ip", err: fmt.Errorf(`ent: validator failed for field "Event.ip": %w`, err)}
		}
	}
	if v, ok := ec.mutation.UserAgent(); ok {
		if err := event.UserAgentValidator(v); err != nil {
			return &ValidationError{Name: "user_agent", err: fmt.Errorf(`ent: validator failed for field "Event.user_agent": %w`, err)}
		}
	}
	return nil
}

func (ec *EventCreate) sqlSave(ctx context.Context) (*Event, error) {
	if err := ec.check(); err != nil {
		return nil, err
	}
	_node, _spec := ec.createSpec()
	if err := sqlgraph.CreateNode(ctx, ec.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ec.mutation.id = &_node.ID
	ec.mutation.done = true
	return _node, nil
}

func (ec *EventCreate) createSpec() (*Event, *sqlgraph.CreateSpec) {
	var (
		_node = &Event{config: ec.config}
		_spec = sqlgraph.NewCreateSpec(event.Table, sqlgraph.NewFieldSpec(event.FieldID, field.TypeInt))
	)

	if id, ok := ec.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = ec.conflict
	if value, ok := ec.mutation.CreatedAt(); ok {
		_spec.SetField(event.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ec.mutation.UpdatedAt(); ok {
		_spec.SetField(event.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := ec.mutation.DeletedAt(); ok {
		_spec.SetField(event.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := ec.mutation.GetType(); ok {
		_spec.SetField(event.FieldType, field.TypeInt, value)
		_node.Type = value
	}
	if value, ok := ec.mutation.CorrelationID(); ok {
		_spec.SetField(event.FieldCorrelationID, field.TypeString, value)
		_node.CorrelationID = value
	}
	if value, ok := ec.mutation.IP(); ok {
		_spec.SetField(event.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := ec.mutation.UserAgent(); ok {
		_spec.SetField(event.FieldUserAgent, field.TypeString, value)
		_node.UserAgent = value
	}
	if value, ok := ec.mutation.Content(); ok {
		_spec.SetField(event.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if nodes := ec.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.UserTable,
			Columns: []string{event.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserEvents = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.FileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.FileTable,
			Columns: []string{event.FileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(file.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.FileEvents = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.EntityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.EntityTable,
			Columns: []string{event.EntityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(entity.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.EntityEvents = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ec.mutation.ShareIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   event.ShareTable,
			Columns: []string{event.ShareColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(share.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ShareEvents = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ec *EventCreate) OnConflict(opts ...sql.ConflictOption) *EventUpsertOne {
	ec.conflict = opts
	return &EventUpsertOne{
		create: ec,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ec *EventCreate) OnConflictColumns(columns ...string) *EventUpsertOne {
	ec.conflict = append(ec.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertOne{
		create: ec,
	}
}

type (
	// EventUpsertOne is the builder for "upsert"-ing
	//  one Event node.
	EventUpsertOne struct {
		create *EventCreate
	}

	// EventUpsert is the "OnConflict" setter.
	EventUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsert) SetUpdatedAt(v time.Time) *EventUpsert {
	u.Set(event.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsert) UpdateUpdatedAt() *EventUpsert {
	u.SetExcluded(event.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventUpsert) SetDeletedAt(v time.Time) *EventUpsert {
	u.Set(event.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventUpsert) UpdateDeletedAt() *EventUpsert {
	u.SetExcluded(event.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventUpsert) ClearDeletedAt() *EventUpsert {
	u.SetNull(event.FieldDeletedAt)
	return u
}

// SetType sets the "type" field.
func (u *EventUpsert) SetType(v int) *EventUpsert {
	u.Set(event.FieldType, v)
	return u
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EventUpsert) UpdateType() *EventUpsert {
	u.SetExcluded(event.FieldType)
	return u
}

// AddType adds v to the "type" field.
func (u *EventUpsert) AddType(v int) *EventUpsert {
	u.Add(event.FieldType, v)
	return u
}

// SetCorrelationID sets the "correlation_id" field.
func (u *EventUpsert) SetCorrelationID(v string) *EventUpsert {
	u.Set(event.FieldCorrelationID, v)
	return u
}

// UpdateCorrelationID sets the "correlation_id" field to the value that was provided on create.
func (u *EventUpsert) UpdateCorrelationID() *EventUpsert {
	u.SetExcluded(event.FieldCorrelationID)
	return u
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (u *EventUpsert) ClearCorrelationID() *EventUpsert {
	u.SetNull(event.FieldCorrelationID)
	return u
}

// SetIP sets the "ip" field.
func (u *EventUpsert) SetIP(v string) *EventUpsert {
	u.Set(event.FieldIP, v)
	return u
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *EventUpsert) UpdateIP() *EventUpsert {
	u.SetExcluded(event.FieldIP)
	return u
}

// ClearIP clears the value of the "ip" field.
func (u *EventUpsert) ClearIP() *EventUpsert {
	u.SetNull(event.FieldIP)
	return u
}

// SetUserAgent sets the "user_agent" field.
func (u *EventUpsert) SetUserAgent(v string) *EventUpsert {
	u.Set(event.FieldUserAgent, v)
	return u
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *EventUpsert) UpdateUserAgent() *EventUpsert {
	u.SetExcluded(event.FieldUserAgent)
	return u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *EventUpsert) ClearUserAgent() *EventUpsert {
	u.SetNull(event.FieldUserAgent)
	return u
}

// SetContent sets the "content" field.
func (u *EventUpsert) SetContent(v *types.AuditContent) *EventUpsert {
	u.Set(event.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *EventUpsert) UpdateContent() *EventUpsert {
	u.SetExcluded(event.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *EventUpsert) ClearContent() *EventUpsert {
	u.SetNull(event.FieldContent)
	return u
}

// SetUserEvents sets the "user_events" field.
func (u *EventUpsert) SetUserEvents(v int) *EventUpsert {
	u.Set(event.FieldUserEvents, v)
	return u
}

// UpdateUserEvents sets the "user_events" field to the value that was provided on create.
func (u *EventUpsert) UpdateUserEvents() *EventUpsert {
	u.SetExcluded(event.FieldUserEvents)
	return u
}

// ClearUserEvents clears the value of the "user_events" field.
func (u *EventUpsert) ClearUserEvents() *EventUpsert {
	u.SetNull(event.FieldUserEvents)
	return u
}

// SetFileEvents sets the "file_events" field.
func (u *EventUpsert) SetFileEvents(v int) *EventUpsert {
	u.Set(event.FieldFileEvents, v)
	return u
}

// UpdateFileEvents sets the "file_events" field to the value that was provided on create.
func (u *EventUpsert) UpdateFileEvents() *EventUpsert {
	u.SetExcluded(event.FieldFileEvents)
	return u
}

// ClearFileEvents clears the value of the "file_events" field.
func (u *EventUpsert) ClearFileEvents() *EventUpsert {
	u.SetNull(event.FieldFileEvents)
	return u
}

// SetEntityEvents sets the "entity_events" field.
func (u *EventUpsert) SetEntityEvents(v int) *EventUpsert {
	u.Set(event.FieldEntityEvents, v)
	return u
}

// UpdateEntityEvents sets the "entity_events" field to the value that was provided on create.
func (u *EventUpsert) UpdateEntityEvents() *EventUpsert {
	u.SetExcluded(event.FieldEntityEvents)
	return u
}

// ClearEntityEvents clears the value of the "entity_events" field.
func (u *EventUpsert) ClearEntityEvents() *EventUpsert {
	u.SetNull(event.FieldEntityEvents)
	return u
}

// SetShareEvents sets the "share_events" field.
func (u *EventUpsert) SetShareEvents(v int) *EventUpsert {
	u.Set(event.FieldShareEvents, v)
	return u
}

// UpdateShareEvents sets the "share_events" field to the value that was provided on create.
func (u *EventUpsert) UpdateShareEvents() *EventUpsert {
	u.SetExcluded(event.FieldShareEvents)
	return u
}

// ClearShareEvents clears the value of the "share_events" field.
func (u *EventUpsert) ClearShareEvents() *EventUpsert {
	u.SetNull(event.FieldShareEvents)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventUpsertOne) UpdateNewValues() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(event.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *EventUpsertOne) Ignore() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertOne) DoNothing() *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreate.OnConflict
// documentation for more info.
func (u *EventUpsertOne) Update(set func(*EventUpsert)) *EventUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsertOne) SetUpdatedAt(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateUpdatedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventUpsertOne) SetDeletedAt(v time.Time) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateDeletedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventUpsertOne) ClearDeletedAt() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetType sets the "type" field.
func (u *EventUpsertOne) SetType(v int) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *EventUpsertOne) AddType(v int) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateType() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateType()
	})
}

// SetCorrelationID sets the "correlation_id" field.
func (u *EventUpsertOne) SetCorrelationID(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetCorrelationID(v)
	})
}

// UpdateCorrelationID sets the "correlation_id" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateCorrelationID() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCorrelationID()
	})
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (u *EventUpsertOne) ClearCorrelationID() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearCorrelationID()
	})
}

// SetIP sets the "ip" field.
func (u *EventUpsertOne) SetIP(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateIP() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *EventUpsertOne) ClearIP() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *EventUpsertOne) SetUserAgent(v string) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateUserAgent() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *EventUpsertOne) ClearUserAgent() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearUserAgent()
	})
}

// SetContent sets the "content" field.
func (u *EventUpsertOne) SetContent(v *types.AuditContent) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateContent() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *EventUpsertOne) ClearContent() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearContent()
	})
}

// SetUserEvents sets the "user_events" field.
func (u *EventUpsertOne) SetUserEvents(v int) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetUserEvents(v)
	})
}

// UpdateUserEvents sets the "user_events" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateUserEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUserEvents()
	})
}

// ClearUserEvents clears the value of the "user_events" field.
func (u *EventUpsertOne) ClearUserEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearUserEvents()
	})
}

// SetFileEvents sets the "file_events" field.
func (u *EventUpsertOne) SetFileEvents(v int) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetFileEvents(v)
	})
}

// UpdateFileEvents sets the "file_events" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateFileEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateFileEvents()
	})
}

// ClearFileEvents clears the value of the "file_events" field.
func (u *EventUpsertOne) ClearFileEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearFileEvents()
	})
}

// SetEntityEvents sets the "entity_events" field.
func (u *EventUpsertOne) SetEntityEvents(v int) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetEntityEvents(v)
	})
}

// UpdateEntityEvents sets the "entity_events" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateEntityEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateEntityEvents()
	})
}

// ClearEntityEvents clears the value of the "entity_events" field.
func (u *EventUpsertOne) ClearEntityEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearEntityEvents()
	})
}

// SetShareEvents sets the "share_events" field.
func (u *EventUpsertOne) SetShareEvents(v int) *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.SetShareEvents(v)
	})
}

// UpdateShareEvents sets the "share_events" field to the value that was provided on create.
func (u *EventUpsertOne) UpdateShareEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.UpdateShareEvents()
	})
}

// ClearShareEvents clears the value of the "share_events" field.
func (u *EventUpsertOne) ClearShareEvents() *EventUpsertOne {
	return u.Update(func(s *EventUpsert) {
		s.ClearShareEvents()
	})
}

// Exec executes the query.
func (u *EventUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *EventUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *EventUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *EventCreate) SetRawID(t int) *EventCreate {
	m.mutation.SetRawID(t)
	return m
}

// EventCreateBulk is the builder for creating many Event entities in bulk.
type EventCreateBulk struct {
	config
	err      error
	builders []*EventCreate
	conflict []sql.ConflictOption
}

// Save creates the Event entities in the database.
func (ecb *EventCreateBulk) Save(ctx context.Context) ([]*Event, error) {
	if ecb.err != nil {
		return nil, ecb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ecb.builders))
	nodes := make([]*Event, len(ecb.builders))
	mutators := make([]Mutator, len(ecb.builders))
	for i := range ecb.builders {
		func(i int, root context.Context) {
			builder := ecb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ecb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ecb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ecb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ecb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ecb *EventCreateBulk) SaveX(ctx context.Context) []*Event {
	v, err := ecb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ecb *EventCreateBulk) Exec(ctx context.Context) error {
	_, err := ecb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ecb *EventCreateBulk) ExecX(ctx context.Context) {
	if err := ecb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Event.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.EventUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ecb *EventCreateBulk) OnConflict(opts ...sql.ConflictOption) *EventUpsertBulk {
	ecb.conflict = opts
	return &EventUpsertBulk{
		create: ecb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ecb *EventCreateBulk) OnConflictColumns(columns ...string) *EventUpsertBulk {
	ecb.conflict = append(ecb.conflict, sql.ConflictColumns(columns...))
	return &EventUpsertBulk{
		create: ecb,
	}
}

// EventUpsertBulk is the builder for "upsert"-ing
// a bulk of Event nodes.
type EventUpsertBulk struct {
	create *EventCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *EventUpsertBulk) UpdateNewValues() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(event.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Event.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *EventUpsertBulk) Ignore() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *EventUpsertBulk) DoNothing() *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the EventCreateBulk.OnConflict
// documentation for more info.
func (u *EventUpsertBulk) Update(set func(*EventUpsert)) *EventUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&EventUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *EventUpsertBulk) SetUpdatedAt(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateUpdatedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *EventUpsertBulk) SetDeletedAt(v time.Time) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateDeletedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *EventUpsertBulk) ClearDeletedAt() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearDeletedAt()
	})
}

// SetType sets the "type" field.
func (u *EventUpsertBulk) SetType(v int) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetType(v)
	})
}

// AddType adds v to the "type" field.
func (u *EventUpsertBulk) AddType(v int) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.AddType(v)
	})
}

// UpdateType sets the "type" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateType() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateType()
	})
}

// SetCorrelationID sets the "correlation_id" field.
func (u *EventUpsertBulk) SetCorrelationID(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetCorrelationID(v)
	})
}

// UpdateCorrelationID sets the "correlation_id" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateCorrelationID() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateCorrelationID()
	})
}

// ClearCorrelationID clears the value of the "correlation_id" field.
func (u *EventUpsertBulk) ClearCorrelationID() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearCorrelationID()
	})
}

// SetIP sets the "ip" field.
func (u *EventUpsertBulk) SetIP(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetIP(v)
	})
}

// UpdateIP sets the "ip" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateIP() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateIP()
	})
}

// ClearIP clears the value of the "ip" field.
func (u *EventUpsertBulk) ClearIP() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearIP()
	})
}

// SetUserAgent sets the "user_agent" field.
func (u *EventUpsertBulk) SetUserAgent(v string) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetUserAgent(v)
	})
}

// UpdateUserAgent sets the "user_agent" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateUserAgent() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUserAgent()
	})
}

// ClearUserAgent clears the value of the "user_agent" field.
func (u *EventUpsertBulk) ClearUserAgent() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearUserAgent()
	})
}

// SetContent sets the "content" field.
func (u *EventUpsertBulk) SetContent(v *types.AuditContent) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateContent() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *EventUpsertBulk) ClearContent() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearContent()
	})
}

// SetUserEvents sets the "user_events" field.
func (u *EventUpsertBulk) SetUserEvents(v int) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetUserEvents(v)
	})
}

// UpdateUserEvents sets the "user_events" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateUserEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateUserEvents()
	})
}

// ClearUserEvents clears the value of the "user_events" field.
func (u *EventUpsertBulk) ClearUserEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearUserEvents()
	})
}

// SetFileEvents sets the "file_events" field.
func (u *EventUpsertBulk) SetFileEvents(v int) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetFileEvents(v)
	})
}

// UpdateFileEvents sets the "file_events" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateFileEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateFileEvents()
	})
}

// ClearFileEvents clears the value of the "file_events" field.
func (u *EventUpsertBulk) ClearFileEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearFileEvents()
	})
}

// SetEntityEvents sets the "entity_events" field.
func (u *EventUpsertBulk) SetEntityEvents(v int) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetEntityEvents(v)
	})
}

// UpdateEntityEvents sets the "entity_events" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateEntityEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateEntityEvents()
	})
}

// ClearEntityEvents clears the value of the "entity_events" field.
func (u *EventUpsertBulk) ClearEntityEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearEntityEvents()
	})
}

// SetShareEvents sets the "share_events" field.
func (u *EventUpsertBulk) SetShareEvents(v int) *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.SetShareEvents(v)
	})
}

// UpdateShareEvents sets the "share_events" field to the value that was provided on create.
func (u *EventUpsertBulk) UpdateShareEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.UpdateShareEvents()
	})
}

// ClearShareEvents clears the value of the "share_events" field.
func (u *EventUpsertBulk) ClearShareEvents() *EventUpsertBulk {
	return u.Update(func(s *EventUpsert) {
		s.ClearShareEvents()
	})
}

// Exec executes the query.
func (u *EventUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the EventCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for EventCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *EventUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
