// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/cloudreve/Cloudreve/v4/ent/giftcode"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// GiftCode is the model entity for the GiftCode schema.
type GiftCode struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Props holds the value of the "props" field.
	Props *types.GiftCodeProps `json:"props,omitempty"`
	// UsedBy holds the value of the "used_by" field.
	UsedBy int `json:"used_by,omitempty"`
	// UsedAt holds the value of the "used_at" field.
	UsedAt *time.Time `json:"used_at,omitempty"`
	// UserCodes holds the value of the "user_codes" field.
	UserCodes int `json:"user_codes,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GiftCodeQuery when eager-loading is set.
	Edges        GiftCodeEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GiftCodeEdges holds the relations/edges for other nodes in the graph.
type GiftCodeEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GiftCodeEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[0] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GiftCode) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case giftcode.FieldProps:
			values[i] = new([]byte)
		case giftcode.FieldID, giftcode.FieldUsedBy, giftcode.FieldUserCodes:
			values[i] = new(sql.NullInt64)
		case giftcode.FieldCode:
			values[i] = new(sql.NullString)
		case giftcode.FieldCreatedAt, giftcode.FieldUpdatedAt, giftcode.FieldDeletedAt, giftcode.FieldUsedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GiftCode fields.
func (gc *GiftCode) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case giftcode.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gc.ID = int(value.Int64)
		case giftcode.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				gc.CreatedAt = value.Time
			}
		case giftcode.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				gc.UpdatedAt = value.Time
			}
		case giftcode.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				gc.DeletedAt = new(time.Time)
				*gc.DeletedAt = value.Time
			}
		case giftcode.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				gc.Code = value.String
			}
		case giftcode.FieldProps:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field props", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &gc.Props); err != nil {
					return fmt.Errorf("unmarshal field props: %w", err)
				}
			}
		case giftcode.FieldUsedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field used_by", values[i])
			} else if value.Valid {
				gc.UsedBy = int(value.Int64)
			}
		case giftcode.FieldUsedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field used_at", values[i])
			} else if value.Valid {
				gc.UsedAt = new(time.Time)
				*gc.UsedAt = value.Time
			}
		case giftcode.FieldUserCodes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_codes", values[i])
			} else if value.Valid {
				gc.UserCodes = int(value.Int64)
			}
		default:
			gc.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GiftCode.
// This includes values selected through modifiers, order, etc.
func (gc *GiftCode) Value(name string) (ent.Value, error) {
	return gc.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the GiftCode entity.
func (gc *GiftCode) QueryUser() *UserQuery {
	return NewGiftCodeClient(gc.config).QueryUser(gc)
}

// Update returns a builder for updating this GiftCode.
// Note that you need to call GiftCode.Unwrap() before calling this method if this GiftCode
// was returned from a transaction, and the transaction was committed or rolled back.
func (gc *GiftCode) Update() *GiftCodeUpdateOne {
	return NewGiftCodeClient(gc.config).UpdateOne(gc)
}

// Unwrap unwraps the GiftCode entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gc *GiftCode) Unwrap() *GiftCode {
	_tx, ok := gc.config.driver.(*txDriver)
	if !ok {
		panic("ent: GiftCode is not a transactional entity")
	}
	gc.config.driver = _tx.drv
	return gc
}

// String implements the fmt.Stringer.
func (gc *GiftCode) String() string {
	var builder strings.Builder
	builder.WriteString("GiftCode(")
	builder.WriteString(fmt.Sprintf("id=%v, ", gc.ID))
	builder.WriteString("created_at=")
	builder.WriteString(gc.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(gc.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := gc.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(gc.Code)
	builder.WriteString(", ")
	builder.WriteString("props=")
	builder.WriteString(fmt.Sprintf("%v", gc.Props))
	builder.WriteString(", ")
	builder.WriteString("used_by=")
	builder.WriteString(fmt.Sprintf("%v", gc.UsedBy))
	builder.WriteString(", ")
	if v := gc.UsedAt; v != nil {
		builder.WriteString("used_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("user_codes=")
	builder.WriteString(fmt.Sprintf("%v", gc.UserCodes))
	builder.WriteByte(')')
	return builder.String()
}

// SetUser manually set the edge as loaded state.
func (e *GiftCode) SetUser(v *User) {
	e.Edges.User = v
	e.Edges.loadedTypes[0] = true
}

// GiftCodes is a parsable slice of GiftCode.
type GiftCodes []*GiftCode
