// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/order"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// OrderCreate is the builder for creating a Order entity.
type OrderCreate struct {
	config
	mutation *OrderMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (oc *OrderCreate) SetCreatedAt(t time.Time) *OrderCreate {
	oc.mutation.SetCreatedAt(t)
	return oc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (oc *OrderCreate) SetNillableCreatedAt(t *time.Time) *OrderCreate {
	if t != nil {
		oc.SetCreatedAt(*t)
	}
	return oc
}

// SetUpdatedAt sets the "updated_at" field.
func (oc *OrderCreate) SetUpdatedAt(t time.Time) *OrderCreate {
	oc.mutation.SetUpdatedAt(t)
	return oc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (oc *OrderCreate) SetNillableUpdatedAt(t *time.Time) *OrderCreate {
	if t != nil {
		oc.SetUpdatedAt(*t)
	}
	return oc
}

// SetDeletedAt sets the "deleted_at" field.
func (oc *OrderCreate) SetDeletedAt(t time.Time) *OrderCreate {
	oc.mutation.SetDeletedAt(t)
	return oc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (oc *OrderCreate) SetNillableDeletedAt(t *time.Time) *OrderCreate {
	if t != nil {
		oc.SetDeletedAt(*t)
	}
	return oc
}

// SetOrderNo sets the "order_no" field.
func (oc *OrderCreate) SetOrderNo(s string) *OrderCreate {
	oc.mutation.SetOrderNo(s)
	return oc
}

// SetProductType sets the "product_type" field.
func (oc *OrderCreate) SetProductType(ot order.ProductType) *OrderCreate {
	oc.mutation.SetProductType(ot)
	return oc
}

// SetProductID sets the "product_id" field.
func (oc *OrderCreate) SetProductID(i int) *OrderCreate {
	oc.mutation.SetProductID(i)
	return oc
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (oc *OrderCreate) SetNillableProductID(i *int) *OrderCreate {
	if i != nil {
		oc.SetProductID(*i)
	}
	return oc
}

// SetQuantity sets the "quantity" field.
func (oc *OrderCreate) SetQuantity(i int) *OrderCreate {
	oc.mutation.SetQuantity(i)
	return oc
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (oc *OrderCreate) SetNillableQuantity(i *int) *OrderCreate {
	if i != nil {
		oc.SetQuantity(*i)
	}
	return oc
}

// SetAmount sets the "amount" field.
func (oc *OrderCreate) SetAmount(i int) *OrderCreate {
	oc.mutation.SetAmount(i)
	return oc
}

// SetStatus sets the "status" field.
func (oc *OrderCreate) SetStatus(o order.Status) *OrderCreate {
	oc.mutation.SetStatus(o)
	return oc
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (oc *OrderCreate) SetNillableStatus(o *order.Status) *OrderCreate {
	if o != nil {
		oc.SetStatus(*o)
	}
	return oc
}

// SetProvider sets the "provider" field.
func (oc *OrderCreate) SetProvider(s string) *OrderCreate {
	oc.mutation.SetProvider(s)
	return oc
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (oc *OrderCreate) SetNillableProvider(s *string) *OrderCreate {
	if s != nil {
		oc.SetProvider(*s)
	}
	return oc
}

// SetContent sets the "content" field.
func (oc *OrderCreate) SetContent(tcp *types.GiftCodeProps) *OrderCreate {
	oc.mutation.SetContent(tcp)
	return oc
}

// SetUserOrders sets the "user_orders" field.
func (oc *OrderCreate) SetUserOrders(i int) *OrderCreate {
	oc.mutation.SetUserOrders(i)
	return oc
}

// SetNillableUserOrders sets the "user_orders" field if the given value is not nil.
func (oc *OrderCreate) SetNillableUserOrders(i *int) *OrderCreate {
	if i != nil {
		oc.SetUserOrders(*i)
	}
	return oc
}

// SetUserID sets the "user" edge to the User entity by ID.
func (oc *OrderCreate) SetUserID(id int) *OrderCreate {
	oc.mutation.SetUserID(id)
	return oc
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (oc *OrderCreate) SetNillableUserID(id *int) *OrderCreate {
	if id != nil {
		oc = oc.SetUserID(*id)
	}
	return oc
}

// SetUser sets the "user" edge to the User entity.
func (oc *OrderCreate) SetUser(u *User) *OrderCreate {
	return oc.SetUserID(u.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (oc *OrderCreate) Mutation() *OrderMutation {
	return oc.mutation
}

// Save creates the Order in the database.
func (oc *OrderCreate) Save(ctx context.Context) (*Order, error) {
	if err := oc.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, oc.sqlSave, oc.mutation, oc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (oc *OrderCreate) SaveX(ctx context.Context) *Order {
	v, err := oc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (oc *OrderCreate) Exec(ctx context.Context) error {
	_, err := oc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (oc *OrderCreate) ExecX(ctx context.Context) {
	if err := oc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (oc *OrderCreate) defaults() error {
	if _, ok := oc.mutation.CreatedAt(); !ok {
		if order.DefaultCreatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.DefaultCreatedAt (forgotten import ent/runtime?)")
		}
		v := order.DefaultCreatedAt()
		oc.mutation.SetCreatedAt(v)
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		if order.DefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.DefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.DefaultUpdatedAt()
		oc.mutation.SetUpdatedAt(v)
	}
	if _, ok := oc.mutation.Quantity(); !ok {
		v := order.DefaultQuantity
		oc.mutation.SetQuantity(v)
	}
	if _, ok := oc.mutation.Status(); !ok {
		v := order.DefaultStatus
		oc.mutation.SetStatus(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (oc *OrderCreate) check() error {
	if _, ok := oc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Order.created_at"`)}
	}
	if _, ok := oc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Order.updated_at"`)}
	}
	if _, ok := oc.mutation.OrderNo(); !ok {
		return &ValidationError{Name: "order_no", err: errors.New(`ent: missing required field "Order.order_no"`)}
	}
	if _, ok := oc.mutation.ProductType(); !ok {
		return &ValidationError{Name: "product_type", err: errors.New(`ent: missing required field "Order.product_type"`)}
	}
	if v, ok := oc.mutation.ProductType(); ok {
		if err := order.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Order.product_type": %w`, err)}
		}
	}
	if _, ok := oc.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "Order.quantity"`)}
	}
	if _, ok := oc.mutation.Amount(); !ok {
		return &ValidationError{Name: "amount", err: errors.New(`ent: missing required field "Order.amount"`)}
	}
	if _, ok := oc.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Order.status"`)}
	}
	if v, ok := oc.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	return nil
}

func (oc *OrderCreate) sqlSave(ctx context.Context) (*Order, error) {
	if err := oc.check(); err != nil {
		return nil, err
	}
	_node, _spec := oc.createSpec()
	if err := sqlgraph.CreateNode(ctx, oc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	oc.mutation.id = &_node.ID
	oc.mutation.done = true
	return _node, nil
}

func (oc *OrderCreate) createSpec() (*Order, *sqlgraph.CreateSpec) {
	var (
		_node = &Order{config: oc.config}
		_spec = sqlgraph.NewCreateSpec(order.Table, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	)

	if id, ok := oc.mutation.ID(); ok {
		_node.ID = id
		id64 := int64(id)
		_spec.ID.Value = id64
	}

	_spec.OnConflict = oc.conflict
	if value, ok := oc.mutation.CreatedAt(); ok {
		_spec.SetField(order.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := oc.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := oc.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := oc.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
		_node.OrderNo = value
	}
	if value, ok := oc.mutation.ProductType(); ok {
		_spec.SetField(order.FieldProductType, field.TypeEnum, value)
		_node.ProductType = value
	}
	if value, ok := oc.mutation.ProductID(); ok {
		_spec.SetField(order.FieldProductID, field.TypeInt, value)
		_node.ProductID = value
	}
	if value, ok := oc.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeInt, value)
		_node.Quantity = value
	}
	if value, ok := oc.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt, value)
		_node.Amount = value
	}
	if value, ok := oc.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := oc.mutation.Provider(); ok {
		_spec.SetField(order.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := oc.mutation.Content(); ok {
		_spec.SetField(order.FieldContent, field.TypeJSON, value)
		_node.Content = value
	}
	if nodes := oc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserOrders = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (oc *OrderCreate) OnConflict(opts ...sql.ConflictOption) *OrderUpsertOne {
	oc.conflict = opts
	return &OrderUpsertOne{
		create: oc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (oc *OrderCreate) OnConflictColumns(columns ...string) *OrderUpsertOne {
	oc.conflict = append(oc.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertOne{
		create: oc,
	}
}

type (
	// OrderUpsertOne is the builder for "upsert"-ing
	//  one Order node.
	OrderUpsertOne struct {
		create *OrderCreate
	}

	// OrderUpsert is the "OnConflict" setter.
	OrderUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsert) SetUpdatedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUpdatedAt() *OrderUpsert {
	u.SetExcluded(order.FieldUpdatedAt)
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsert) SetDeletedAt(v time.Time) *OrderUpsert {
	u.Set(order.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsert) UpdateDeletedAt() *OrderUpsert {
	u.SetExcluded(order.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsert) ClearDeletedAt() *OrderUpsert {
	u.SetNull(order.FieldDeletedAt)
	return u
}

// SetOrderNo sets the "order_no" field.
func (u *OrderUpsert) SetOrderNo(v string) *OrderUpsert {
	u.Set(order.FieldOrderNo, v)
	return u
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *OrderUpsert) UpdateOrderNo() *OrderUpsert {
	u.SetExcluded(order.FieldOrderNo)
	return u
}

// SetProductType sets the "product_type" field.
func (u *OrderUpsert) SetProductType(v order.ProductType) *OrderUpsert {
	u.Set(order.FieldProductType, v)
	return u
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *OrderUpsert) UpdateProductType() *OrderUpsert {
	u.SetExcluded(order.FieldProductType)
	return u
}

// SetProductID sets the "product_id" field.
func (u *OrderUpsert) SetProductID(v int) *OrderUpsert {
	u.Set(order.FieldProductID, v)
	return u
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *OrderUpsert) UpdateProductID() *OrderUpsert {
	u.SetExcluded(order.FieldProductID)
	return u
}

// AddProductID adds v to the "product_id" field.
func (u *OrderUpsert) AddProductID(v int) *OrderUpsert {
	u.Add(order.FieldProductID, v)
	return u
}

// ClearProductID clears the value of the "product_id" field.
func (u *OrderUpsert) ClearProductID() *OrderUpsert {
	u.SetNull(order.FieldProductID)
	return u
}

// SetQuantity sets the "quantity" field.
func (u *OrderUpsert) SetQuantity(v int) *OrderUpsert {
	u.Set(order.FieldQuantity, v)
	return u
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *OrderUpsert) UpdateQuantity() *OrderUpsert {
	u.SetExcluded(order.FieldQuantity)
	return u
}

// AddQuantity adds v to the "quantity" field.
func (u *OrderUpsert) AddQuantity(v int) *OrderUpsert {
	u.Add(order.FieldQuantity, v)
	return u
}

// SetAmount sets the "amount" field.
func (u *OrderUpsert) SetAmount(v int) *OrderUpsert {
	u.Set(order.FieldAmount, v)
	return u
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsert) UpdateAmount() *OrderUpsert {
	u.SetExcluded(order.FieldAmount)
	return u
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsert) AddAmount(v int) *OrderUpsert {
	u.Add(order.FieldAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *OrderUpsert) SetStatus(v order.Status) *OrderUpsert {
	u.Set(order.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsert) UpdateStatus() *OrderUpsert {
	u.SetExcluded(order.FieldStatus)
	return u
}

// SetProvider sets the "provider" field.
func (u *OrderUpsert) SetProvider(v string) *OrderUpsert {
	u.Set(order.FieldProvider, v)
	return u
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OrderUpsert) UpdateProvider() *OrderUpsert {
	u.SetExcluded(order.FieldProvider)
	return u
}

// ClearProvider clears the value of the "provider" field.
func (u *OrderUpsert) ClearProvider() *OrderUpsert {
	u.SetNull(order.FieldProvider)
	return u
}

// SetContent sets the "content" field.
func (u *OrderUpsert) SetContent(v *types.GiftCodeProps) *OrderUpsert {
	u.Set(order.FieldContent, v)
	return u
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *OrderUpsert) UpdateContent() *OrderUpsert {
	u.SetExcluded(order.FieldContent)
	return u
}

// ClearContent clears the value of the "content" field.
func (u *OrderUpsert) ClearContent() *OrderUpsert {
	u.SetNull(order.FieldContent)
	return u
}

// SetUserOrders sets the "user_orders" field.
func (u *OrderUpsert) SetUserOrders(v int) *OrderUpsert {
	u.Set(order.FieldUserOrders, v)
	return u
}

// UpdateUserOrders sets the "user_orders" field to the value that was provided on create.
func (u *OrderUpsert) UpdateUserOrders() *OrderUpsert {
	u.SetExcluded(order.FieldUserOrders)
	return u
}

// ClearUserOrders clears the value of the "user_orders" field.
func (u *OrderUpsert) ClearUserOrders() *OrderUpsert {
	u.SetNull(order.FieldUserOrders)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertOne) UpdateNewValues() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(order.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *OrderUpsertOne) Ignore() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertOne) DoNothing() *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreate.OnConflict
// documentation for more info.
func (u *OrderUpsertOne) Update(set func(*OrderUpsert)) *OrderUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertOne) SetUpdatedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUpdatedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsertOne) SetDeletedAt(v time.Time) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateDeletedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsertOne) ClearDeletedAt() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *OrderUpsertOne) SetOrderNo(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateOrderNo() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetProductType sets the "product_type" field.
func (u *OrderUpsertOne) SetProductType(v order.ProductType) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductType(v)
	})
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateProductType() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductType()
	})
}

// SetProductID sets the "product_id" field.
func (u *OrderUpsertOne) SetProductID(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductID(v)
	})
}

// AddProductID adds v to the "product_id" field.
func (u *OrderUpsertOne) AddProductID(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateProductID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *OrderUpsertOne) ClearProductID() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearProductID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *OrderUpsertOne) SetQuantity(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *OrderUpsertOne) AddQuantity(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateQuantity() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateQuantity()
	})
}

// SetAmount sets the "amount" field.
func (u *OrderUpsertOne) SetAmount(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsertOne) AddAmount(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateAmount() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertOne) SetStatus(v order.Status) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateStatus() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *OrderUpsertOne) SetProvider(v string) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateProvider() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *OrderUpsertOne) ClearProvider() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearProvider()
	})
}

// SetContent sets the "content" field.
func (u *OrderUpsertOne) SetContent(v *types.GiftCodeProps) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateContent() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *OrderUpsertOne) ClearContent() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearContent()
	})
}

// SetUserOrders sets the "user_orders" field.
func (u *OrderUpsertOne) SetUserOrders(v int) *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserOrders(v)
	})
}

// UpdateUserOrders sets the "user_orders" field to the value that was provided on create.
func (u *OrderUpsertOne) UpdateUserOrders() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserOrders()
	})
}

// ClearUserOrders clears the value of the "user_orders" field.
func (u *OrderUpsertOne) ClearUserOrders() *OrderUpsertOne {
	return u.Update(func(s *OrderUpsert) {
		s.ClearUserOrders()
	})
}

// Exec executes the query.
func (u *OrderUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *OrderUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *OrderUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

func (m *OrderCreate) SetRawID(t int) *OrderCreate {
	m.mutation.SetRawID(t)
	return m
}

// OrderCreateBulk is the builder for creating many Order entities in bulk.
type OrderCreateBulk struct {
	config
	err      error
	builders []*OrderCreate
	conflict []sql.ConflictOption
}

// Save creates the Order entities in the database.
func (ocb *OrderCreateBulk) Save(ctx context.Context) ([]*Order, error) {
	if ocb.err != nil {
		return nil, ocb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ocb.builders))
	nodes := make([]*Order, len(ocb.builders))
	mutators := make([]Mutator, len(ocb.builders))
	for i := range ocb.builders {
		func(i int, root context.Context) {
			builder := ocb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ocb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = ocb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ocb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ocb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ocb *OrderCreateBulk) SaveX(ctx context.Context) []*Order {
	v, err := ocb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ocb *OrderCreateBulk) Exec(ctx context.Context) error {
	_, err := ocb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ocb *OrderCreateBulk) ExecX(ctx context.Context) {
	if err := ocb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Order.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.OrderUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (ocb *OrderCreateBulk) OnConflict(opts ...sql.ConflictOption) *OrderUpsertBulk {
	ocb.conflict = opts
	return &OrderUpsertBulk{
		create: ocb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (ocb *OrderCreateBulk) OnConflictColumns(columns ...string) *OrderUpsertBulk {
	ocb.conflict = append(ocb.conflict, sql.ConflictColumns(columns...))
	return &OrderUpsertBulk{
		create: ocb,
	}
}

// OrderUpsertBulk is the builder for "upsert"-ing
// a bulk of Order nodes.
type OrderUpsertBulk struct {
	create *OrderCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *OrderUpsertBulk) UpdateNewValues() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(order.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Order.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *OrderUpsertBulk) Ignore() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *OrderUpsertBulk) DoNothing() *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the OrderCreateBulk.OnConflict
// documentation for more info.
func (u *OrderUpsertBulk) Update(set func(*OrderUpsert)) *OrderUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&OrderUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *OrderUpsertBulk) SetUpdatedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUpdatedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetDeletedAt sets the "deleted_at" field.
func (u *OrderUpsertBulk) SetDeletedAt(v time.Time) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateDeletedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *OrderUpsertBulk) ClearDeletedAt() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearDeletedAt()
	})
}

// SetOrderNo sets the "order_no" field.
func (u *OrderUpsertBulk) SetOrderNo(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetOrderNo(v)
	})
}

// UpdateOrderNo sets the "order_no" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateOrderNo() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateOrderNo()
	})
}

// SetProductType sets the "product_type" field.
func (u *OrderUpsertBulk) SetProductType(v order.ProductType) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductType(v)
	})
}

// UpdateProductType sets the "product_type" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateProductType() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductType()
	})
}

// SetProductID sets the "product_id" field.
func (u *OrderUpsertBulk) SetProductID(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetProductID(v)
	})
}

// AddProductID adds v to the "product_id" field.
func (u *OrderUpsertBulk) AddProductID(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddProductID(v)
	})
}

// UpdateProductID sets the "product_id" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateProductID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProductID()
	})
}

// ClearProductID clears the value of the "product_id" field.
func (u *OrderUpsertBulk) ClearProductID() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearProductID()
	})
}

// SetQuantity sets the "quantity" field.
func (u *OrderUpsertBulk) SetQuantity(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetQuantity(v)
	})
}

// AddQuantity adds v to the "quantity" field.
func (u *OrderUpsertBulk) AddQuantity(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddQuantity(v)
	})
}

// UpdateQuantity sets the "quantity" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateQuantity() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateQuantity()
	})
}

// SetAmount sets the "amount" field.
func (u *OrderUpsertBulk) SetAmount(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetAmount(v)
	})
}

// AddAmount adds v to the "amount" field.
func (u *OrderUpsertBulk) AddAmount(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.AddAmount(v)
	})
}

// UpdateAmount sets the "amount" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateAmount() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateAmount()
	})
}

// SetStatus sets the "status" field.
func (u *OrderUpsertBulk) SetStatus(v order.Status) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateStatus() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateStatus()
	})
}

// SetProvider sets the "provider" field.
func (u *OrderUpsertBulk) SetProvider(v string) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetProvider(v)
	})
}

// UpdateProvider sets the "provider" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateProvider() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateProvider()
	})
}

// ClearProvider clears the value of the "provider" field.
func (u *OrderUpsertBulk) ClearProvider() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearProvider()
	})
}

// SetContent sets the "content" field.
func (u *OrderUpsertBulk) SetContent(v *types.GiftCodeProps) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetContent(v)
	})
}

// UpdateContent sets the "content" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateContent() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateContent()
	})
}

// ClearContent clears the value of the "content" field.
func (u *OrderUpsertBulk) ClearContent() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearContent()
	})
}

// SetUserOrders sets the "user_orders" field.
func (u *OrderUpsertBulk) SetUserOrders(v int) *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.SetUserOrders(v)
	})
}

// UpdateUserOrders sets the "user_orders" field to the value that was provided on create.
func (u *OrderUpsertBulk) UpdateUserOrders() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.UpdateUserOrders()
	})
}

// ClearUserOrders clears the value of the "user_orders" field.
func (u *OrderUpsertBulk) ClearUserOrders() *OrderUpsertBulk {
	return u.Update(func(s *OrderUpsert) {
		s.ClearUserOrders()
	})
}

// Exec executes the query.
func (u *OrderUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the OrderCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for OrderCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *OrderUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
