// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/cloudreve/Cloudreve/v4/ent/order"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
	"github.com/cloudreve/Cloudreve/v4/ent/user"
	"github.com/cloudreve/Cloudreve/v4/inventory/types"
)

// OrderUpdate is the builder for updating Order entities.
type OrderUpdate struct {
	config
	hooks    []Hook
	mutation *OrderMutation
}

// Where appends a list predicates to the OrderUpdate builder.
func (ou *OrderUpdate) Where(ps ...predicate.Order) *OrderUpdate {
	ou.mutation.Where(ps...)
	return ou
}

// SetUpdatedAt sets the "updated_at" field.
func (ou *OrderUpdate) SetUpdatedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetUpdatedAt(t)
	return ou
}

// SetDeletedAt sets the "deleted_at" field.
func (ou *OrderUpdate) SetDeletedAt(t time.Time) *OrderUpdate {
	ou.mutation.SetDeletedAt(t)
	return ou
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableDeletedAt(t *time.Time) *OrderUpdate {
	if t != nil {
		ou.SetDeletedAt(*t)
	}
	return ou
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ou *OrderUpdate) ClearDeletedAt() *OrderUpdate {
	ou.mutation.ClearDeletedAt()
	return ou
}

// SetOrderNo sets the "order_no" field.
func (ou *OrderUpdate) SetOrderNo(s string) *OrderUpdate {
	ou.mutation.SetOrderNo(s)
	return ou
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableOrderNo(s *string) *OrderUpdate {
	if s != nil {
		ou.SetOrderNo(*s)
	}
	return ou
}

// SetProductType sets the "product_type" field.
func (ou *OrderUpdate) SetProductType(ot order.ProductType) *OrderUpdate {
	ou.mutation.SetProductType(ot)
	return ou
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableProductType(ot *order.ProductType) *OrderUpdate {
	if ot != nil {
		ou.SetProductType(*ot)
	}
	return ou
}

// SetProductID sets the "product_id" field.
func (ou *OrderUpdate) SetProductID(i int) *OrderUpdate {
	ou.mutation.ResetProductID()
	ou.mutation.SetProductID(i)
	return ou
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableProductID(i *int) *OrderUpdate {
	if i != nil {
		ou.SetProductID(*i)
	}
	return ou
}

// AddProductID adds i to the "product_id" field.
func (ou *OrderUpdate) AddProductID(i int) *OrderUpdate {
	ou.mutation.AddProductID(i)
	return ou
}

// ClearProductID clears the value of the "product_id" field.
func (ou *OrderUpdate) ClearProductID() *OrderUpdate {
	ou.mutation.ClearProductID()
	return ou
}

// SetQuantity sets the "quantity" field.
func (ou *OrderUpdate) SetQuantity(i int) *OrderUpdate {
	ou.mutation.ResetQuantity()
	ou.mutation.SetQuantity(i)
	return ou
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableQuantity(i *int) *OrderUpdate {
	if i != nil {
		ou.SetQuantity(*i)
	}
	return ou
}

// AddQuantity adds i to the "quantity" field.
func (ou *OrderUpdate) AddQuantity(i int) *OrderUpdate {
	ou.mutation.AddQuantity(i)
	return ou
}

// SetAmount sets the "amount" field.
func (ou *OrderUpdate) SetAmount(i int) *OrderUpdate {
	ou.mutation.ResetAmount()
	ou.mutation.SetAmount(i)
	return ou
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableAmount(i *int) *OrderUpdate {
	if i != nil {
		ou.SetAmount(*i)
	}
	return ou
}

// AddAmount adds i to the "amount" field.
func (ou *OrderUpdate) AddAmount(i int) *OrderUpdate {
	ou.mutation.AddAmount(i)
	return ou
}

// SetStatus sets the "status" field.
func (ou *OrderUpdate) SetStatus(o order.Status) *OrderUpdate {
	ou.mutation.SetStatus(o)
	return ou
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableStatus(o *order.Status) *OrderUpdate {
	if o != nil {
		ou.SetStatus(*o)
	}
	return ou
}

// SetProvider sets the "provider" field.
func (ou *OrderUpdate) SetProvider(s string) *OrderUpdate {
	ou.mutation.SetProvider(s)
	return ou
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableProvider(s *string) *OrderUpdate {
	if s != nil {
		ou.SetProvider(*s)
	}
	return ou
}

// ClearProvider clears the value of the "provider" field.
func (ou *OrderUpdate) ClearProvider() *OrderUpdate {
	ou.mutation.ClearProvider()
	return ou
}

// SetContent sets the "content" field.
func (ou *OrderUpdate) SetContent(tcp *types.GiftCodeProps) *OrderUpdate {
	ou.mutation.SetContent(tcp)
	return ou
}

// ClearContent clears the value of the "content" field.
func (ou *OrderUpdate) ClearContent() *OrderUpdate {
	ou.mutation.ClearContent()
	return ou
}

// SetUserOrders sets the "user_orders" field.
func (ou *OrderUpdate) SetUserOrders(i int) *OrderUpdate {
	ou.mutation.SetUserOrders(i)
	return ou
}

// SetNillableUserOrders sets the "user_orders" field if the given value is not nil.
func (ou *OrderUpdate) SetNillableUserOrders(i *int) *OrderUpdate {
	if i != nil {
		ou.SetUserOrders(*i)
	}
	return ou
}

// ClearUserOrders clears the value of the "user_orders" field.
func (ou *OrderUpdate) ClearUserOrders() *OrderUpdate {
	ou.mutation.ClearUserOrders()
	return ou
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ou *OrderUpdate) SetUserID(id int) *OrderUpdate {
	ou.mutation.SetUserID(id)
	return ou
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (ou *OrderUpdate) SetNillableUserID(id *int) *OrderUpdate {
	if id != nil {
		ou = ou.SetUserID(*id)
	}
	return ou
}

// SetUser sets the "user" edge to the User entity.
func (ou *OrderUpdate) SetUser(u *User) *OrderUpdate {
	return ou.SetUserID(u.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ou *OrderUpdate) Mutation() *OrderMutation {
	return ou.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ou *OrderUpdate) ClearUser() *OrderUpdate {
	ou.mutation.ClearUser()
	return ou
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ou *OrderUpdate) Save(ctx context.Context) (int, error) {
	if err := ou.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, ou.sqlSave, ou.mutation, ou.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ou *OrderUpdate) SaveX(ctx context.Context) int {
	affected, err := ou.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ou *OrderUpdate) Exec(ctx context.Context) error {
	_, err := ou.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ou *OrderUpdate) ExecX(ctx context.Context) {
	if err := ou.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ou *OrderUpdate) defaults() error {
	if _, ok := ou.mutation.UpdatedAt(); !ok {
		if order.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.UpdateDefaultUpdatedAt()
		ou.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ou *OrderUpdate) check() error {
	if v, ok := ou.mutation.ProductType(); ok {
		if err := order.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Order.product_type": %w`, err)}
		}
	}
	if v, ok := ou.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	return nil
}

func (ou *OrderUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ou.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	if ps := ou.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ou.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ou.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if ou.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ou.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := ou.mutation.ProductType(); ok {
		_spec.SetField(order.FieldProductType, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.ProductID(); ok {
		_spec.SetField(order.FieldProductID, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedProductID(); ok {
		_spec.AddField(order.FieldProductID, field.TypeInt, value)
	}
	if ou.mutation.ProductIDCleared() {
		_spec.ClearField(order.FieldProductID, field.TypeInt)
	}
	if value, ok := ou.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedQuantity(); ok {
		_spec.AddField(order.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ou.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ou.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ou.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ou.mutation.Provider(); ok {
		_spec.SetField(order.FieldProvider, field.TypeString, value)
	}
	if ou.mutation.ProviderCleared() {
		_spec.ClearField(order.FieldProvider, field.TypeString)
	}
	if value, ok := ou.mutation.Content(); ok {
		_spec.SetField(order.FieldContent, field.TypeJSON, value)
	}
	if ou.mutation.ContentCleared() {
		_spec.ClearField(order.FieldContent, field.TypeJSON)
	}
	if ou.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ou.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ou.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ou.mutation.done = true
	return n, nil
}

// OrderUpdateOne is the builder for updating a single Order entity.
type OrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrderMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (ouo *OrderUpdateOne) SetUpdatedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetUpdatedAt(t)
	return ouo
}

// SetDeletedAt sets the "deleted_at" field.
func (ouo *OrderUpdateOne) SetDeletedAt(t time.Time) *OrderUpdateOne {
	ouo.mutation.SetDeletedAt(t)
	return ouo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableDeletedAt(t *time.Time) *OrderUpdateOne {
	if t != nil {
		ouo.SetDeletedAt(*t)
	}
	return ouo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ouo *OrderUpdateOne) ClearDeletedAt() *OrderUpdateOne {
	ouo.mutation.ClearDeletedAt()
	return ouo
}

// SetOrderNo sets the "order_no" field.
func (ouo *OrderUpdateOne) SetOrderNo(s string) *OrderUpdateOne {
	ouo.mutation.SetOrderNo(s)
	return ouo
}

// SetNillableOrderNo sets the "order_no" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableOrderNo(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetOrderNo(*s)
	}
	return ouo
}

// SetProductType sets the "product_type" field.
func (ouo *OrderUpdateOne) SetProductType(ot order.ProductType) *OrderUpdateOne {
	ouo.mutation.SetProductType(ot)
	return ouo
}

// SetNillableProductType sets the "product_type" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableProductType(ot *order.ProductType) *OrderUpdateOne {
	if ot != nil {
		ouo.SetProductType(*ot)
	}
	return ouo
}

// SetProductID sets the "product_id" field.
func (ouo *OrderUpdateOne) SetProductID(i int) *OrderUpdateOne {
	ouo.mutation.ResetProductID()
	ouo.mutation.SetProductID(i)
	return ouo
}

// SetNillableProductID sets the "product_id" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableProductID(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetProductID(*i)
	}
	return ouo
}

// AddProductID adds i to the "product_id" field.
func (ouo *OrderUpdateOne) AddProductID(i int) *OrderUpdateOne {
	ouo.mutation.AddProductID(i)
	return ouo
}

// ClearProductID clears the value of the "product_id" field.
func (ouo *OrderUpdateOne) ClearProductID() *OrderUpdateOne {
	ouo.mutation.ClearProductID()
	return ouo
}

// SetQuantity sets the "quantity" field.
func (ouo *OrderUpdateOne) SetQuantity(i int) *OrderUpdateOne {
	ouo.mutation.ResetQuantity()
	ouo.mutation.SetQuantity(i)
	return ouo
}

// SetNillableQuantity sets the "quantity" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableQuantity(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetQuantity(*i)
	}
	return ouo
}

// AddQuantity adds i to the "quantity" field.
func (ouo *OrderUpdateOne) AddQuantity(i int) *OrderUpdateOne {
	ouo.mutation.AddQuantity(i)
	return ouo
}

// SetAmount sets the "amount" field.
func (ouo *OrderUpdateOne) SetAmount(i int) *OrderUpdateOne {
	ouo.mutation.ResetAmount()
	ouo.mutation.SetAmount(i)
	return ouo
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableAmount(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetAmount(*i)
	}
	return ouo
}

// AddAmount adds i to the "amount" field.
func (ouo *OrderUpdateOne) AddAmount(i int) *OrderUpdateOne {
	ouo.mutation.AddAmount(i)
	return ouo
}

// SetStatus sets the "status" field.
func (ouo *OrderUpdateOne) SetStatus(o order.Status) *OrderUpdateOne {
	ouo.mutation.SetStatus(o)
	return ouo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableStatus(o *order.Status) *OrderUpdateOne {
	if o != nil {
		ouo.SetStatus(*o)
	}
	return ouo
}

// SetProvider sets the "provider" field.
func (ouo *OrderUpdateOne) SetProvider(s string) *OrderUpdateOne {
	ouo.mutation.SetProvider(s)
	return ouo
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableProvider(s *string) *OrderUpdateOne {
	if s != nil {
		ouo.SetProvider(*s)
	}
	return ouo
}

// ClearProvider clears the value of the "provider" field.
func (ouo *OrderUpdateOne) ClearProvider() *OrderUpdateOne {
	ouo.mutation.ClearProvider()
	return ouo
}

// SetContent sets the "content" field.
func (ouo *OrderUpdateOne) SetContent(tcp *types.GiftCodeProps) *OrderUpdateOne {
	ouo.mutation.SetContent(tcp)
	return ouo
}

// ClearContent clears the value of the "content" field.
func (ouo *OrderUpdateOne) ClearContent() *OrderUpdateOne {
	ouo.mutation.ClearContent()
	return ouo
}

// SetUserOrders sets the "user_orders" field.
func (ouo *OrderUpdateOne) SetUserOrders(i int) *OrderUpdateOne {
	ouo.mutation.SetUserOrders(i)
	return ouo
}

// SetNillableUserOrders sets the "user_orders" field if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableUserOrders(i *int) *OrderUpdateOne {
	if i != nil {
		ouo.SetUserOrders(*i)
	}
	return ouo
}

// ClearUserOrders clears the value of the "user_orders" field.
func (ouo *OrderUpdateOne) ClearUserOrders() *OrderUpdateOne {
	ouo.mutation.ClearUserOrders()
	return ouo
}

// SetUserID sets the "user" edge to the User entity by ID.
func (ouo *OrderUpdateOne) SetUserID(id int) *OrderUpdateOne {
	ouo.mutation.SetUserID(id)
	return ouo
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (ouo *OrderUpdateOne) SetNillableUserID(id *int) *OrderUpdateOne {
	if id != nil {
		ouo = ouo.SetUserID(*id)
	}
	return ouo
}

// SetUser sets the "user" edge to the User entity.
func (ouo *OrderUpdateOne) SetUser(u *User) *OrderUpdateOne {
	return ouo.SetUserID(u.ID)
}

// Mutation returns the OrderMutation object of the builder.
func (ouo *OrderUpdateOne) Mutation() *OrderMutation {
	return ouo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (ouo *OrderUpdateOne) ClearUser() *OrderUpdateOne {
	ouo.mutation.ClearUser()
	return ouo
}

// Where appends a list predicates to the OrderUpdate builder.
func (ouo *OrderUpdateOne) Where(ps ...predicate.Order) *OrderUpdateOne {
	ouo.mutation.Where(ps...)
	return ouo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ouo *OrderUpdateOne) Select(field string, fields ...string) *OrderUpdateOne {
	ouo.fields = append([]string{field}, fields...)
	return ouo
}

// Save executes the query and returns the updated Order entity.
func (ouo *OrderUpdateOne) Save(ctx context.Context) (*Order, error) {
	if err := ouo.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, ouo.sqlSave, ouo.mutation, ouo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ouo *OrderUpdateOne) SaveX(ctx context.Context) *Order {
	node, err := ouo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ouo *OrderUpdateOne) Exec(ctx context.Context) error {
	_, err := ouo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ouo *OrderUpdateOne) ExecX(ctx context.Context) {
	if err := ouo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ouo *OrderUpdateOne) defaults() error {
	if _, ok := ouo.mutation.UpdatedAt(); !ok {
		if order.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized order.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := order.UpdateDefaultUpdatedAt()
		ouo.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (ouo *OrderUpdateOne) check() error {
	if v, ok := ouo.mutation.ProductType(); ok {
		if err := order.ProductTypeValidator(v); err != nil {
			return &ValidationError{Name: "product_type", err: fmt.Errorf(`ent: validator failed for field "Order.product_type": %w`, err)}
		}
	}
	if v, ok := ouo.mutation.Status(); ok {
		if err := order.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Order.status": %w`, err)}
		}
	}
	return nil
}

func (ouo *OrderUpdateOne) sqlSave(ctx context.Context) (_node *Order, err error) {
	if err := ouo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(order.Table, order.Columns, sqlgraph.NewFieldSpec(order.FieldID, field.TypeInt))
	id, ok := ouo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Order.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ouo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, order.FieldID)
		for _, f := range fields {
			if !order.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != order.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ouo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ouo.mutation.UpdatedAt(); ok {
		_spec.SetField(order.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ouo.mutation.DeletedAt(); ok {
		_spec.SetField(order.FieldDeletedAt, field.TypeTime, value)
	}
	if ouo.mutation.DeletedAtCleared() {
		_spec.ClearField(order.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := ouo.mutation.OrderNo(); ok {
		_spec.SetField(order.FieldOrderNo, field.TypeString, value)
	}
	if value, ok := ouo.mutation.ProductType(); ok {
		_spec.SetField(order.FieldProductType, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.ProductID(); ok {
		_spec.SetField(order.FieldProductID, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedProductID(); ok {
		_spec.AddField(order.FieldProductID, field.TypeInt, value)
	}
	if ouo.mutation.ProductIDCleared() {
		_spec.ClearField(order.FieldProductID, field.TypeInt)
	}
	if value, ok := ouo.mutation.Quantity(); ok {
		_spec.SetField(order.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedQuantity(); ok {
		_spec.AddField(order.FieldQuantity, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.Amount(); ok {
		_spec.SetField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.AddedAmount(); ok {
		_spec.AddField(order.FieldAmount, field.TypeInt, value)
	}
	if value, ok := ouo.mutation.Status(); ok {
		_spec.SetField(order.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := ouo.mutation.Provider(); ok {
		_spec.SetField(order.FieldProvider, field.TypeString, value)
	}
	if ouo.mutation.ProviderCleared() {
		_spec.ClearField(order.FieldProvider, field.TypeString)
	}
	if value, ok := ouo.mutation.Content(); ok {
		_spec.SetField(order.FieldContent, field.TypeJSON, value)
	}
	if ouo.mutation.ContentCleared() {
		_spec.ClearField(order.FieldContent, field.TypeJSON)
	}
	if ouo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ouo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   order.UserTable,
			Columns: []string{order.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Order{config: ouo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ouo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{order.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ouo.mutation.done = true
	return _node, nil
}
