// Code generated by ent, DO NOT EDIT.

package giftcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldDeletedAt, v))
}

// Code applies equality check predicate on the "code" field. It's identical to CodeEQ.
func Code(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCode, v))
}

// UsedBy applies equality check predicate on the "used_by" field. It's identical to UsedByEQ.
func UsedBy(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedBy, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedAt, v))
}

// UserCodes applies equality check predicate on the "user_codes" field. It's identical to UserCodesEQ.
func UserCodes(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUserCodes, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldDeletedAt))
}

// CodeEQ applies the EQ predicate on the "code" field.
func CodeEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldCode, v))
}

// CodeNEQ applies the NEQ predicate on the "code" field.
func CodeNEQ(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldCode, v))
}

// CodeIn applies the In predicate on the "code" field.
func CodeIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldCode, vs...))
}

// CodeNotIn applies the NotIn predicate on the "code" field.
func CodeNotIn(vs ...string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldCode, vs...))
}

// CodeGT applies the GT predicate on the "code" field.
func CodeGT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldCode, v))
}

// CodeGTE applies the GTE predicate on the "code" field.
func CodeGTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldCode, v))
}

// CodeLT applies the LT predicate on the "code" field.
func CodeLT(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldCode, v))
}

// CodeLTE applies the LTE predicate on the "code" field.
func CodeLTE(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldCode, v))
}

// CodeContains applies the Contains predicate on the "code" field.
func CodeContains(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContains(FieldCode, v))
}

// CodeHasPrefix applies the HasPrefix predicate on the "code" field.
func CodeHasPrefix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasPrefix(FieldCode, v))
}

// CodeHasSuffix applies the HasSuffix predicate on the "code" field.
func CodeHasSuffix(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldHasSuffix(FieldCode, v))
}

// CodeEqualFold applies the EqualFold predicate on the "code" field.
func CodeEqualFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEqualFold(FieldCode, v))
}

// CodeContainsFold applies the ContainsFold predicate on the "code" field.
func CodeContainsFold(v string) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldContainsFold(FieldCode, v))
}

// PropsIsNil applies the IsNil predicate on the "props" field.
func PropsIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldProps))
}

// PropsNotNil applies the NotNil predicate on the "props" field.
func PropsNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldProps))
}

// UsedByEQ applies the EQ predicate on the "used_by" field.
func UsedByEQ(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedBy, v))
}

// UsedByNEQ applies the NEQ predicate on the "used_by" field.
func UsedByNEQ(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUsedBy, v))
}

// UsedByIn applies the In predicate on the "used_by" field.
func UsedByIn(vs ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldUsedBy, vs...))
}

// UsedByNotIn applies the NotIn predicate on the "used_by" field.
func UsedByNotIn(vs ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldUsedBy, vs...))
}

// UsedByGT applies the GT predicate on the "used_by" field.
func UsedByGT(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldUsedBy, v))
}

// UsedByGTE applies the GTE predicate on the "used_by" field.
func UsedByGTE(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldUsedBy, v))
}

// UsedByLT applies the LT predicate on the "used_by" field.
func UsedByLT(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldUsedBy, v))
}

// UsedByLTE applies the LTE predicate on the "used_by" field.
func UsedByLTE(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldUsedBy, v))
}

// UsedByIsNil applies the IsNil predicate on the "used_by" field.
func UsedByIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldUsedBy))
}

// UsedByNotNil applies the NotNil predicate on the "used_by" field.
func UsedByNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldUsedBy))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldUsedAt))
}

// UserCodesEQ applies the EQ predicate on the "user_codes" field.
func UserCodesEQ(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldEQ(FieldUserCodes, v))
}

// UserCodesNEQ applies the NEQ predicate on the "user_codes" field.
func UserCodesNEQ(v int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNEQ(FieldUserCodes, v))
}

// UserCodesIn applies the In predicate on the "user_codes" field.
func UserCodesIn(vs ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIn(FieldUserCodes, vs...))
}

// UserCodesNotIn applies the NotIn predicate on the "user_codes" field.
func UserCodesNotIn(vs ...int) predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotIn(FieldUserCodes, vs...))
}

// UserCodesIsNil applies the IsNil predicate on the "user_codes" field.
func UserCodesIsNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldIsNull(FieldUserCodes))
}

// UserCodesNotNil applies the NotNil predicate on the "user_codes" field.
func UserCodesNotNil() predicate.GiftCode {
	return predicate.GiftCode(sql.FieldNotNull(FieldUserCodes))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.GiftCode {
	return predicate.GiftCode(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.GiftCode {
	return predicate.GiftCode(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GiftCode) predicate.GiftCode {
	return predicate.GiftCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GiftCode) predicate.GiftCode {
	return predicate.GiftCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GiftCode) predicate.GiftCode {
	return predicate.GiftCode(sql.NotPredicates(p))
}
