// Code generated by ent, DO NOT EDIT.

package abusereport

import (
	"fmt"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the abusereport type in the database.
	Label = "abuse_report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldFolderPath holds the string denoting the folder_path field in the database.
	FieldFolderPath = "folder_path"
	// FieldReason holds the string denoting the reason field in the database.
	FieldReason = "reason"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRawContent holds the string denoting the raw_content field in the database.
	FieldRawContent = "raw_content"
	// FieldReporterUser holds the string denoting the reporter_user field in the database.
	FieldReporterUser = "reporter_user"
	// FieldReportedUser holds the string denoting the reported_user field in the database.
	FieldReportedUser = "reported_user"
	// FieldShareReports holds the string denoting the share_reports field in the database.
	FieldShareReports = "share_reports"
	// EdgeReporter holds the string denoting the reporter edge name in mutations.
	EdgeReporter = "reporter"
	// EdgeReported holds the string denoting the reported edge name in mutations.
	EdgeReported = "reported"
	// EdgeShare holds the string denoting the share edge name in mutations.
	EdgeShare = "share"
	// Table holds the table name of the abusereport in the database.
	Table = "abuse_reports"
	// ReporterTable is the table that holds the reporter relation/edge.
	ReporterTable = "abuse_reports"
	// ReporterInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReporterInverseTable = "users"
	// ReporterColumn is the table column denoting the reporter relation/edge.
	ReporterColumn = "reporter_user"
	// ReportedTable is the table that holds the reported relation/edge.
	ReportedTable = "abuse_reports"
	// ReportedInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	ReportedInverseTable = "users"
	// ReportedColumn is the table column denoting the reported relation/edge.
	ReportedColumn = "reported_user"
	// ShareTable is the table that holds the share relation/edge.
	ShareTable = "abuse_reports"
	// ShareInverseTable is the table name for the Share entity.
	// It exists in this package in order to avoid circular dependency with the "share" package.
	ShareInverseTable = "shares"
	// ShareColumn is the table column denoting the share relation/edge.
	ShareColumn = "share_reports"
)

// Columns holds all SQL columns for abusereport fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldFolderPath,
	FieldReason,
	FieldDescription,
	FieldStatus,
	FieldRawContent,
	FieldReporterUser,
	FieldReportedUser,
	FieldShareReports,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/cloudreve/Cloudreve/v4/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPending is the default value of the Status enum.
const DefaultStatus = StatusPending

// Status values.
const (
	StatusPending  Status = "pending"
	StatusResolved Status = "resolved"
	StatusIgnored  Status = "ignored"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusPending, StatusResolved, StatusIgnored:
		return nil
	default:
		return fmt.Errorf("abusereport: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AbuseReport queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByFolderPath orders the results by the folder_path field.
func ByFolderPath(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFolderPath, opts...).ToFunc()
}

// ByReason orders the results by the reason field.
func ByReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReason, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByReporterUser orders the results by the reporter_user field.
func ByReporterUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReporterUser, opts...).ToFunc()
}

// ByReportedUser orders the results by the reported_user field.
func ByReportedUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedUser, opts...).ToFunc()
}

// ByShareReports orders the results by the share_reports field.
func ByShareReports(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShareReports, opts...).ToFunc()
}

// ByReporterField orders the results by reporter field.
func ByReporterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReporterStep(), sql.OrderByField(field, opts...))
	}
}

// ByReportedField orders the results by reported field.
func ByReportedField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReportedStep(), sql.OrderByField(field, opts...))
	}
}

// ByShareField orders the results by share field.
func ByShareField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newShareStep(), sql.OrderByField(field, opts...))
	}
}
func newReporterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReporterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReporterTable, ReporterColumn),
	)
}
func newReportedStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReportedInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReportedTable, ReportedColumn),
	)
}
func newShareStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ShareInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ShareTable, ShareColumn),
	)
}
