// Code generated by ent, DO NOT EDIT.

package abusereport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/cloudreve/Cloudreve/v4/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldDeletedAt, v))
}

// FolderPath applies equality check predicate on the "folder_path" field. It's identical to FolderPathEQ.
func FolderPath(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldFolderPath, v))
}

// Reason applies equality check predicate on the "reason" field. It's identical to ReasonEQ.
func Reason(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReason, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldDescription, v))
}

// ReporterUser applies equality check predicate on the "reporter_user" field. It's identical to ReporterUserEQ.
func ReporterUser(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReporterUser, v))
}

// ReportedUser applies equality check predicate on the "reported_user" field. It's identical to ReportedUserEQ.
func ReportedUser(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReportedUser, v))
}

// ShareReports applies equality check predicate on the "share_reports" field. It's identical to ShareReportsEQ.
func ShareReports(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldShareReports, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldDeletedAt))
}

// FolderPathEQ applies the EQ predicate on the "folder_path" field.
func FolderPathEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldFolderPath, v))
}

// FolderPathNEQ applies the NEQ predicate on the "folder_path" field.
func FolderPathNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldFolderPath, v))
}

// FolderPathIn applies the In predicate on the "folder_path" field.
func FolderPathIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldFolderPath, vs...))
}

// FolderPathNotIn applies the NotIn predicate on the "folder_path" field.
func FolderPathNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldFolderPath, vs...))
}

// FolderPathGT applies the GT predicate on the "folder_path" field.
func FolderPathGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldFolderPath, v))
}

// FolderPathGTE applies the GTE predicate on the "folder_path" field.
func FolderPathGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldFolderPath, v))
}

// FolderPathLT applies the LT predicate on the "folder_path" field.
func FolderPathLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldFolderPath, v))
}

// FolderPathLTE applies the LTE predicate on the "folder_path" field.
func FolderPathLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldFolderPath, v))
}

// FolderPathContains applies the Contains predicate on the "folder_path" field.
func FolderPathContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldFolderPath, v))
}

// FolderPathHasPrefix applies the HasPrefix predicate on the "folder_path" field.
func FolderPathHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldFolderPath, v))
}

// FolderPathHasSuffix applies the HasSuffix predicate on the "folder_path" field.
func FolderPathHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldFolderPath, v))
}

// FolderPathIsNil applies the IsNil predicate on the "folder_path" field.
func FolderPathIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldFolderPath))
}

// FolderPathNotNil applies the NotNil predicate on the "folder_path" field.
func FolderPathNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldFolderPath))
}

// FolderPathEqualFold applies the EqualFold predicate on the "folder_path" field.
func FolderPathEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldFolderPath, v))
}

// FolderPathContainsFold applies the ContainsFold predicate on the "folder_path" field.
func FolderPathContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldFolderPath, v))
}

// ReasonEQ applies the EQ predicate on the "reason" field.
func ReasonEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReason, v))
}

// ReasonNEQ applies the NEQ predicate on the "reason" field.
func ReasonNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldReason, v))
}

// ReasonIn applies the In predicate on the "reason" field.
func ReasonIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldReason, vs...))
}

// ReasonNotIn applies the NotIn predicate on the "reason" field.
func ReasonNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldReason, vs...))
}

// ReasonGT applies the GT predicate on the "reason" field.
func ReasonGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldReason, v))
}

// ReasonGTE applies the GTE predicate on the "reason" field.
func ReasonGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldReason, v))
}

// ReasonLT applies the LT predicate on the "reason" field.
func ReasonLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldReason, v))
}

// ReasonLTE applies the LTE predicate on the "reason" field.
func ReasonLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldReason, v))
}

// ReasonContains applies the Contains predicate on the "reason" field.
func ReasonContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldReason, v))
}

// ReasonHasPrefix applies the HasPrefix predicate on the "reason" field.
func ReasonHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldReason, v))
}

// ReasonHasSuffix applies the HasSuffix predicate on the "reason" field.
func ReasonHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldReason, v))
}

// ReasonIsNil applies the IsNil predicate on the "reason" field.
func ReasonIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldReason))
}

// ReasonNotNil applies the NotNil predicate on the "reason" field.
func ReasonNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldReason))
}

// ReasonEqualFold applies the EqualFold predicate on the "reason" field.
func ReasonEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldReason, v))
}

// ReasonContainsFold applies the ContainsFold predicate on the "reason" field.
func ReasonContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldReason, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldStatus, vs...))
}

// RawContentIsNil applies the IsNil predicate on the "raw_content" field.
func RawContentIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldRawContent))
}

// RawContentNotNil applies the NotNil predicate on the "raw_content" field.
func RawContentNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldRawContent))
}

// ReporterUserEQ applies the EQ predicate on the "reporter_user" field.
func ReporterUserEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReporterUser, v))
}

// ReporterUserNEQ applies the NEQ predicate on the "reporter_user" field.
func ReporterUserNEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldReporterUser, v))
}

// ReporterUserIn applies the In predicate on the "reporter_user" field.
func ReporterUserIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldReporterUser, vs...))
}

// ReporterUserNotIn applies the NotIn predicate on the "reporter_user" field.
func ReporterUserNotIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldReporterUser, vs...))
}

// ReporterUserIsNil applies the IsNil predicate on the "reporter_user" field.
func ReporterUserIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldReporterUser))
}

// ReporterUserNotNil applies the NotNil predicate on the "reporter_user" field.
func ReporterUserNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldReporterUser))
}

// ReportedUserEQ applies the EQ predicate on the "reported_user" field.
func ReportedUserEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldReportedUser, v))
}

// ReportedUserNEQ applies the NEQ predicate on the "reported_user" field.
func ReportedUserNEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldReportedUser, v))
}

// ReportedUserIn applies the In predicate on the "reported_user" field.
func ReportedUserIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldReportedUser, vs...))
}

// ReportedUserNotIn applies the NotIn predicate on the "reported_user" field.
func ReportedUserNotIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldReportedUser, vs...))
}

// ReportedUserIsNil applies the IsNil predicate on the "reported_user" field.
func ReportedUserIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldReportedUser))
}

// ReportedUserNotNil applies the NotNil predicate on the "reported_user" field.
func ReportedUserNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldReportedUser))
}

// ShareReportsEQ applies the EQ predicate on the "share_reports" field.
func ShareReportsEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldEQ(FieldShareReports, v))
}

// ShareReportsNEQ applies the NEQ predicate on the "share_reports" field.
func ShareReportsNEQ(v int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNEQ(FieldShareReports, v))
}

// ShareReportsIn applies the In predicate on the "share_reports" field.
func ShareReportsIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIn(FieldShareReports, vs...))
}

// ShareReportsNotIn applies the NotIn predicate on the "share_reports" field.
func ShareReportsNotIn(vs ...int) predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotIn(FieldShareReports, vs...))
}

// ShareReportsIsNil applies the IsNil predicate on the "share_reports" field.
func ShareReportsIsNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldIsNull(FieldShareReports))
}

// ShareReportsNotNil applies the NotNil predicate on the "share_reports" field.
func ShareReportsNotNil() predicate.AbuseReport {
	return predicate.AbuseReport(sql.FieldNotNull(FieldShareReports))
}

// HasReporter applies the HasEdge predicate on the "reporter" edge.
func HasReporter() predicate.AbuseReport {
	return predicate.AbuseReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReporterTable, ReporterColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReporterWith applies the HasEdge predicate on the "reporter" edge with a given conditions (other predicates).
func HasReporterWith(preds ...predicate.User) predicate.AbuseReport {
	return predicate.AbuseReport(func(s *sql.Selector) {
		step := newReporterStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReported applies the HasEdge predicate on the "reported" edge.
func HasReported() predicate.AbuseReport {
	return predicate.AbuseReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ReportedTable, ReportedColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReportedWith applies the HasEdge predicate on the "reported" edge with a given conditions (other predicates).
func HasReportedWith(preds ...predicate.User) predicate.AbuseReport {
	return predicate.AbuseReport(func(s *sql.Selector) {
		step := newReportedStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasShare applies the HasEdge predicate on the "share" edge.
func HasShare() predicate.AbuseReport {
	return predicate.AbuseReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ShareTable, ShareColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasShareWith applies the HasEdge predicate on the "share" edge with a given conditions (other predicates).
func HasShareWith(preds ...predicate.Share) predicate.AbuseReport {
	return predicate.AbuseReport(func(s *sql.Selector) {
		step := newShareStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AbuseReport) predicate.AbuseReport {
	return predicate.AbuseReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AbuseReport) predicate.AbuseReport {
	return predicate.AbuseReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AbuseReport) predicate.AbuseReport {
	return predicate.AbuseReport(sql.NotPredicates(p))
}
